// Teste de tela do site de Gestão de Projetos, em navegador automatizado.
// Usa dados de exemplo (supabase-de-mentira.js) e não toca no banco real. Como rodar: ver README.md desta pasta.
import { createRequire } from "module"; import { fileURLToPath } from "url"; import http from "http"; import fs from "fs"; import path from "path";
const aqui = path.dirname(fileURLToPath(import.meta.url));
const raiz = process.env.SITE || path.join(aqui, "..");   // pasta onde está o index.html
let chromium;
try { ({ chromium } = await import("playwright")); }
catch (_) { ({ chromium } = createRequire((process.env.NODE_PATH || ".") + "/")("playwright")); }
const tipos = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".svg": "image/svg+xml", ".png": "image/png" };
const srv = http.createServer((rq, rs) => { const f = path.join(raiz, rq.url.split("?")[0].replace(/\/$/, "/index.html"));
  fs.readFile(f, (e, d) => { if (e) { rs.writeHead(404); rs.end(); } else { rs.writeHead(200, { "content-type": tipos[path.extname(f)] || "application/octet-stream" }); rs.end(d); } }); }).listen(8123);
const b = await chromium.launch(); const pg = await b.newPage(); const erros = [];
pg.on("pageerror", (e) => erros.push("erro: " + e.message)); pg.on("console", (m) => { if (m.type() === "error" && !/404|Failed to load resource/.test(m.text())) erros.push("console: " + m.text()); });
await pg.route("**/*", (r) => { const u = r.request().url();
  if (u.includes("supabase-js")) return r.fulfill({ contentType: "text/javascript", body: fs.readFileSync(path.join(aqui, "supabase-de-mentira.js"), "utf8") });
  if (u.startsWith("http://localhost:8123")) return r.continue(); return r.abort(); });
let ok = 0, falhas = 0; const confere = (nome, cond) => { cond ? ok++ : falhas++; console.log((cond ? "ok    " : "FALHA ") + nome); };
await pg.goto("http://localhost:8123/"); await pg.waitForSelector("#app:not([hidden])", { timeout: 8000 });
const txt = async (s) => (await pg.locator(s).innerText());
confere("entra e mostra o app", await pg.locator("#app").isVisible());
confere("nome e papel na conta", (await txt("#conta-nome")) === "Ana Teste" && (await txt("#conta-papel")) === "Administrador");
confere("avatar com iniciais", (await txt("#conta-avatar")) === "AT");
confere("menu Configurações visível para admin", await pg.locator("#menu-config").isVisible());
confere("quadro de projetos mostra o cartão", (await txt("#visao-projetos")).includes("Projeto Exemplo"));
confere("colunas do quadro", /A FAZER/i.test(await txt("#visao-projetos")) && /CONCLUÍDO/i.test(await txt("#visao-projetos")));
await pg.click("[data-visao='tarefas']");
confere("quadro de tarefas mostra as duas tarefas", (await txt("#visao-tarefas")).includes("Tarefa atrasada") && (await txt("#visao-tarefas")).includes("Tarefa avulsa"));
confere("data curta no cartão (1 jan 2020)", /1 jan 2020/.test(await txt("#visao-tarefas")));
for (const modo of await pg.locator("[data-modo]").all()) { await modo.click(); }
confere("troca de modos de tarefas sem erro", erros.length === 0);
await pg.locator("[data-modo='quadro']").click();
await pg.getByText("Tarefa avulsa").first().click();
confere("abre a janela da tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
confere("histórico na janela", /Criado por Ana Teste em \d\d\/\d\d\/\d{4} às \d\d:\d\d/.test(await txt("#dlg-tarefa")));
await pg.locator("#dlg-tarefa [data-fechar]").first().click();
await pg.click("[data-visao='projetos']"); await pg.getByText("Projeto Exemplo").first().click();
confere("abre a janela do projeto com a tarefa dele", await pg.locator("#dlg-projeto").evaluate((d) => d.open) && (await txt("#dlg-projeto")).includes("Tarefa atrasada"));
await pg.locator("#dlg-projeto [data-fechar]").first().click();
await pg.click("[data-visao='lixeira']"); confere("abre a lixeira", await pg.locator("#visao-lixeira").isVisible());
await pg.click("[data-visao='config']"); confere("abre Configurações com usuários", (await txt("#visao-config")).includes("Bruno Silva"));
await pg.evaluate(() => import("./js/util.js").then((u) => u.aviso("teste de aviso")));
confere("aviso aparece", (await txt("#aviso")) === "teste de aviso");
await pg.click("[data-visao='tarefas']"); await pg.locator("[data-modo='quadro']").click();
const grav = () => pg.evaluate(() => window.__gravacoes);
const antes = (await grav()).length;
await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa avulsa" }).dragTo(pg.locator("#quadro-tarefas .coluna-lista[data-coluna='ct2']"));
await pg.waitForTimeout(300);
const g1 = (await grav()).slice(antes);
confere("arrastar com mouse grava a nova coluna", g1.some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].coluna_id === "ct2"));
confere("estado de arrasto é limpo", await pg.evaluate(() => import("./js/estado.js").then((m) => m.estado.arrastando === null && m.estado.pendente === false)));
await pg.locator("#quadro-tarefas .coluna-novo").first().click();
confere("botão Adicionar tarefa da coluna abre a janela", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
await pg.locator("#dlg-tarefa [data-fechar]").first().click();
const n2 = (await grav()).length;
await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa atrasada" }).locator("button").first().click(); await pg.waitForTimeout(200);
confere("botão de concluir no cartão grava a conclusão", (await grav()).slice(n2).some((x) => x[0] === "tarefas" && x[2] && "concluida_em" in x[2]));
await pg.click("[data-visao='projetos']");
await pg.locator("#quadro-projetos .cartao").first().focus(); await pg.keyboard.press("Enter");
confere("Enter no cartão abre o projeto", await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.locator("#dlg-projeto [data-fechar]").first().click();
confere("opcoesResponsavel removida", await pg.evaluate(() => import("./js/estado.js").then((m) => !("opcoesResponsavel" in m))));
// Etapa 3: janelas e listas de projetos e tarefas
const fechaJanelas = () => pg.evaluate(() => { for (const d of document.querySelectorAll("dialog[open]")) d.close(); });
await fechaJanelas(); await pg.click("[data-visao='tarefas']");
await pg.selectOption("#filtro-projeto", "avulsas"); await pg.locator("[data-modo='quadro']").click();
confere("filtro Somente avulsas esconde a tarefa de projeto", !(await txt("#quadro-tarefas")).includes("Tarefa atrasada") && (await txt("#quadro-tarefas")).includes("Tarefa avulsa"));
await pg.selectOption("#filtro-projeto", "todos");
await pg.locator("[data-modo='lista']").click();
confere("Lista por data mostra o grupo Atrasadas", /Atrasadas/i.test(await txt("#lista-tarefas")));
await pg.locator("#lista-tarefas button.abrir").first().click();
confere("Lista por data abre a tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
let n3 = (await grav()).length;
await pg.fill("#t-titulo", "Tarefa editada"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar tarefa grava o título novo", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].titulo === "Tarefa editada"));
confere("janela da tarefa fecha ao salvar", !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)));
await pg.click("#nova-tarefa");
confere("Nova tarefa abre janela vazia", (await txt("#t-janela")) === "Nova tarefa" && (await pg.inputValue("#t-titulo")) === "");
n3 = (await grav()).length;
await pg.fill("#t-titulo", "Tarefa nova"); await pg.fill("#t-prazo", "2030-05-10"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("criar tarefa grava inserção", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "insert" && x[2].titulo === "Tarefa nova" && x[2].responsavel_id === "u1"));
await fechaJanelas(); await pg.locator("[data-modo='lista']").click(); await pg.locator("#lista-tarefas button.abrir").first().click();
n3 = (await grav()).length; await pg.click("#t-concluir"); await pg.waitForTimeout(200);
confere("concluir pela janela grava a conclusão", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[2] && x[2].concluida_em));
await pg.locator("[data-modo='concluidas']").click(); await pg.fill("#busca-concluidas", "zzz");
confere("busca em Concluídas responde", /Nenhuma tarefa concluída/.test(await txt("#tabela-concluidas")));
await pg.click("[data-visao='projetos']"); await pg.getByText("Projeto Exemplo").first().click();
confere("janela do projeto mostra equipe e histórico", /Bruno Silva/.test(await txt("#p-membros-resumo")) && /Criado por Ana Teste/.test(await txt("#p-historico")));
await pg.locator("#p-lista li button:not(.marcar)").first().click();
confere("tarefa dentro do projeto abre por cima, sem fechar o projeto", await pg.locator("#dlg-tarefa").evaluate((d) => d.open) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click(); await pg.click("#p-adicionar");
confere("Adicionar tarefa no projeto já vem com o projeto", (await pg.inputValue("#t-projeto")) === "p1");
await pg.locator("#dlg-tarefa [data-fechar]").last().click();
confere("cancelar a tarefa volta para o projeto aberto", !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.fill("#p-descricao", "Texto ainda não salvo"); await pg.click("#p-adicionar");
n3 = (await grav()).length; await pg.fill("#t-titulo", "Tarefa pelo projeto"); await pg.fill("#t-prazo", "2030-06-10"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar a tarefa grava no projeto e volta para ele", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "insert" && x[2].projeto_id === "p1") && !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
confere("a descrição digitada no projeto não se perde", (await pg.inputValue("#p-descricao")) === "Texto ainda não salvo");
n3 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("depois da tarefa, salvar o projeto grava a descrição", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].descricao === "Texto ainda não salvo"));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click();
n3 = (await grav()).length; await pg.fill("#p-titulo", "Projeto editado"); await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar projeto grava o título novo", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].titulo === "Projeto editado"));
await pg.click("#novo-projeto");
confere("Novo projeto abre janela vazia", (await txt("#p-janela")) === "Novo projeto");
n3 = (await grav()).length; await pg.fill("#p-titulo", "Projeto novo"); await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("criar projeto grava inserção", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "insert" && x[2].titulo === "Projeto novo"));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click(); await pg.click("#p-excluir");
confere("excluir projeto pede confirmação", await pg.locator("#dlg-confirma").evaluate((d) => d.open));
n3 = (await grav()).length; await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("confirmar exclusão manda para a lixeira", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[2] && x[2].arquivado_em));
await fechaJanelas();
// Etapa 4: lixeiras, Configurações e convites
await pg.reload(); await pg.waitForSelector("#app:not([hidden])");
await pg.click("[data-visao='lixeira']");
confere("minha lixeira lista os itens excluídos", (await txt("#tabela-minha-lixeira")).includes("Tarefa excluída") && /Tarefa avulsa/.test(await txt("#tabela-minha-lixeira")));
n3 = (await grav()).length; await pg.locator("#tabela-minha-lixeira button", { hasText: "Restaurar" }).first().click(); await pg.waitForTimeout(200);
confere("Restaurar na minha lixeira chama restaurar_item", (await grav()).slice(n3).some((x) => x[0] === "rpc" && x[1] === "restaurar_item" && x[2].tabela === "tarefas"));
await pg.click("[data-visao='config']");
confere("Configurações lista usuários e colunas", (await txt("#tabela-usuarios")).includes("Ana Teste (você)") && (await txt("#tabela-colunas-tarefas")).includes("A fazer"));
confere("lixeira geral mostra só tarefa de projeto", (await txt("#tabela-lixeira")).includes("Tarefa de projeto excluída") && !(await txt("#tabela-lixeira")).includes("Tarefa excluída\n"));
n3 = (await grav()).length; await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).getByRole("button", { name: "Bloquear" }).click(); await pg.waitForTimeout(200);
confere("Bloquear usuário grava ativo = false", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].ativo === false));
n3 = (await grav()).length; await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).locator("select").selectOption("admin"); await pg.waitForTimeout(200);
confere("trocar tipo de usuário grava o papel", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].papel === "admin"));
n3 = (await grav()).length; await pg.locator("#tabela-colunas-tarefas tr", { hasText: "A fazer" }).getByRole("button", { name: "Descer" }).click(); await pg.waitForTimeout(200);
confere("Descer coluna grava a nova ordem", (await grav()).slice(n3).some((x) => x[0] === "colunas" && x[2] && "ordem" in x[2]));
await pg.locator("#tabela-colunas-projetos tr", { hasText: "Concluído" }).getByRole("button", { name: "Editar" }).click();
confere("Editar coluna abre a janela preenchida", (await pg.inputValue("#c-nome")) === "Concluído" && await pg.isChecked("#c-concluida"));
n3 = (await grav()).length; await pg.fill("#c-nome", "Feito"); await pg.locator("#form-coluna [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar coluna grava o nome", (await grav()).slice(n3).some((x) => x[0] === "colunas" && x[1] === "update" && x[2].nome === "Feito"));
await pg.locator("[data-nova-coluna]").first().click();
confere("Nova coluna abre a janela vazia", (await txt("#c-janela")) === "Nova coluna" && (await pg.inputValue("#c-nome")) === "");
await fechaJanelas();
await pg.locator("#tabela-colunas-tarefas tr", { hasText: "A fazer" }).getByRole("button", { name: "Excluir" }).click();
confere("excluir coluna com cartões avisa e não apaga", /ainda tem \d+ cart/.test(await txt("#aviso")));
n3 = (await grav()).length; await pg.locator("#tabela-lixeira").getByRole("button", { name: "Excluir de vez" }).first().click();
confere("Excluir de vez pede confirmação", await pg.locator("#dlg-confirma").evaluate((d) => d.open));
await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("confirmar apaga do banco", (await grav()).slice(n3).some((x) => x[1] === "delete"));
n3 = (await grav()).length; await pg.locator("#tabela-lixeira").getByRole("button", { name: "Restaurar" }).first().click(); await pg.waitForTimeout(200);
confere("Restaurar na lixeira geral chama restaurar_item", (await grav()).slice(n3).some((x) => x[0] === "rpc"));
await pg.click("#convidar");
confere("Convidar abre a janela", await pg.locator("#dlg-convite").evaluate((d) => d.open));
await pg.fill("#v-nome", "Carla"); await pg.fill("#v-email", "carla@exemplo.com"); n3 = (await grav()).length; await pg.click("#v-gerar"); await pg.waitForTimeout(300);
confere("gerar convite chama a função e mostra o link", (await grav()).slice(n3).some((x) => x[0] === "funcao" && x[2].acao === "convidar") && /\?convite=tok123&tipo=invite$/.test(await pg.inputValue("#v-link")));
await fechaJanelas(); n3 = (await grav()).length;
await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).getByRole("button", { name: "Gerar novo link" }).click(); await pg.waitForTimeout(300);
confere("Gerar novo link mostra link de nova senha", (await grav()).slice(n3).some((x) => x[0] === "funcao" && x[2].acao === "novo_link") && /tipo=recovery$/.test(await pg.inputValue("#v-link")));
await fechaJanelas();
await pg.click("#btn-conta");
confere("Minha conta abre com o nome", (await pg.inputValue("#m-nome")) === "Ana Teste");
n3 = (await grav()).length; await pg.fill("#m-nome", "Ana T."); await pg.locator("#form-conta [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar Minha conta grava o nome", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].nome === "Ana T."));
await pg.goto("http://localhost:8123/?convite=abc"); await pg.waitForSelector("#tela-senha:not([hidden])");
confere("link de convite abre a tela de criar senha", (await txt("#senha-titulo")) === "Crie a sua senha");
confere("nenhum erro no console", erros.length === 0); erros.forEach((e) => console.log("   " + e));
console.log(`RESULTADO: ${ok} ok, ${falhas} falhas`); await b.close(); srv.close();
process.exit(falhas ? 1 : 0);
