// Teste de tela do site de Gestão de Projetos, em navegador automatizado.
// Usa dados de exemplo (supabase-de-mentira.js) e não toca no banco real. Como rodar: ver README.md desta pasta.
import { createRequire } from "module"; import { fileURLToPath } from "url"; import http from "http"; import fs from "fs"; import path from "path";
const aqui = path.dirname(fileURLToPath(import.meta.url));
const raiz = process.env.SITE || path.join(aqui, "..");   // pasta onde está o index.html
let chromium;
try { ({ chromium } = await import("playwright")); }
catch (_) { ({ chromium } = createRequire((process.env.NODE_PATH || ".") + "/")("playwright")); }
const tipos = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".svg": "image/svg+xml", ".png": "image/png" };
const srv = http.createServer((rq, rs) => { const f = path.join(raiz, rq.url.split("?")[0].replace(/\/$/, "/index.html"));
  fs.readFile(f, (e, d) => { if (e) { rs.writeHead(404); rs.end(); } else { rs.writeHead(200, { "content-type": tipos[path.extname(f)] || "application/octet-stream" }); rs.end(d); } }); }).listen(8123);
const b = await chromium.launch(); const pg = await b.newPage(); const erros = [];
pg.on("pageerror", (e) => erros.push("erro: " + e.message)); pg.on("console", (m) => { if (m.type() === "error" && !/404|Failed to load resource/.test(m.text())) erros.push("console: " + m.text()); });
await pg.route("**/*", (r) => { const u = r.request().url();
  if (u.includes("supabase-js")) return r.fulfill({ contentType: "text/javascript", body: fs.readFileSync(path.join(aqui, "supabase-de-mentira.js"), "utf8") });
  if (u.startsWith("http://localhost:8123")) return r.continue(); return r.abort(); });
let ok = 0, falhas = 0; const confere = (nome, cond) => { cond ? ok++ : falhas++; console.log((cond ? "ok    " : "FALHA ") + nome); };
await pg.goto("http://localhost:8123/"); await pg.waitForSelector("#app:not([hidden])", { timeout: 8000 });
const txt = async (s) => (await pg.locator(s).innerText());
confere("entra e mostra o app", await pg.locator("#app").isVisible());
confere("nome e papel na conta", (await txt("#conta-nome")) === "Ana Teste" && (await txt("#conta-papel")) === "Administrador");
confere("avatar com iniciais", (await txt("#conta-avatar")) === "AT");
confere("iniciais ignoram parênteses no nome", (await pg.evaluate(() => import("./js/estado.js").then((m) => { m.estado.perfis.push({ id: "zz", nome: "Gauten (Admin)" }); const t = m.avatar("zz").textContent; m.estado.perfis.pop(); return t; }))) === "GA");
confere("menu Configurações visível para admin", await pg.locator("#menu-config").isVisible());
confere("quadro de projetos mostra o cartão", (await txt("#visao-projetos")).includes("Projeto Exemplo"));
confere("colunas do quadro", /A FAZER/i.test(await txt("#visao-projetos")) && /CONCLUÍDO/i.test(await txt("#visao-projetos")));
confere("computador: colunas lado a lado, sem etiquetas nem frase do celular", (await pg.locator("#quadro-projetos .coluna:visible").count()) === 2 && !(await pg.locator("#quadro-projetos .etiquetas").isVisible()) && !(await pg.locator("#quadro-projetos .dica-coluna").isVisible()));
confere("cartão de projeto no modelo da tarefa: nome com o responsável, etiquetas e andamento, nessa ordem", (await pg.locator("#quadro-projetos .cartao").first().evaluate((c) => [...c.children].map((x) => x.className).join("|"))) === "topo-projeto|chips|rodape" && (await pg.locator("#quadro-projetos .cartao .chips").first().innerText()).replace(/\s+/g, " ").trim() === "Prioridade alta 2 pessoas 1 jan 2020" && (await pg.locator("#quadro-projetos .cartao .chips .avatar, #quadro-projetos .cartao .rodape .avatar").count()) === 0);
confere("cartão do projeto mostra o progresso por extenso", (await txt("#quadro-projetos .progresso")).includes("0 de 1 tarefa"));
confere("resumo de projetos no cabeçalho", (await txt("#resumo-projetos")) === "1 projeto · 1 atrasado");
await pg.click("[data-visao='tarefas']");
confere("computador: Tarefas abre no Quadro, sem o botão + do celular", (await pg.locator("[data-modo='quadro']").getAttribute("aria-selected")) === "true" && (await txt("[data-modo='lista']")) === "Lista por data" && !(await pg.locator("#botao-novo").isVisible()) && await pg.locator("#nova-tarefa").isVisible());
confere("resumo de tarefas no cabeçalho", (await txt("#resumo-tarefas")) === "2 tarefas abertas · 1 atrasada");
confere("quadro de tarefas mostra as duas tarefas", (await txt("#visao-tarefas")).includes("Tarefa atrasada") && (await txt("#visao-tarefas")).includes("Tarefa avulsa"));
confere("data curta no cartão (1 jan 2020)", /1 jan 2020/.test(await txt("#visao-tarefas")));
confere("cartão de tarefa no modelo da Lista: nome, projeto e etiquetas, nessa ordem", (await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa atrasada" }).evaluate((c) => [...c.children].map((x) => x.className).join("|"))) === "topo-tarefa|origem|chips");
confere("cartão de tarefa e Lista usam as mesmas etiquetas", (await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa atrasada" }).locator(".chips").innerText()).replace(/\s+/g, " ").trim() === "Prioridade média 1 jan 2020");
// O responsável fica na primeira linha, à direita; o nome longo termina em reticências, com folga antes do ícone
const primeiraLinha = (sel, nomeSel) => pg.locator(sel).first().evaluate((c, nomeSel) => { const a = c.querySelector(".avatar"), n = c.querySelector(nomeSel); n.textContent = "Um nome de tarefa comprido o bastante para não caber em uma linha só do cartão ou da lista, de propósito";
  const ra = a.getBoundingClientRect(), rn = n.getBoundingClientRect(), rc = c.getBoundingClientRect();
  return { naLinhaDoNome: ra.top < rn.bottom && ra.bottom > rn.top, aDireita: rc.right - ra.right < 24, folga: ra.left - rn.right, reticencias: getComputedStyle(n).textOverflow === "ellipsis" && n.scrollWidth > n.clientWidth && rn.height < 30 }; }, nomeSel);
const certo = (m) => m.naLinhaDoNome && m.aDireita && m.folga >= 10 && m.reticencias;
await pg.click("[data-visao='projetos']");
confere("cartão de projeto: responsável na primeira linha, à direita, e nome longo com reticências", certo(await primeiraLinha("#quadro-projetos .cartao", ".nome")));
await pg.click("[data-visao='tarefas']");
confere("cartão de tarefa: responsável na primeira linha, à direita, e nome longo com reticências", certo(await primeiraLinha("#quadro-tarefas .cartao", ".nome")));
for (const modo of await pg.locator("[data-modo]").all()) { await modo.click(); }
confere("troca de modos de tarefas sem erro", erros.length === 0);
await pg.locator("[data-modo='lista']").click();
confere("lista por data mostra a coluna de cada tarefa", (await pg.locator("#lista-tarefas .linha-tarefa .chip[title='Coluna no quadro']").count()) === 2);
await pg.locator("[data-modo='quadro']").click();
await pg.getByText("Tarefa avulsa").first().click();
confere("abre a janela da tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
confere("histórico na janela", /Criado por Ana Teste em \d\d\/\d\d\/\d{4} às \d\d:\d\d/.test(await txt("#dlg-tarefa")));
await pg.locator("#dlg-tarefa [data-fechar]").first().click();
await pg.click("[data-visao='projetos']"); await pg.getByText("Projeto Exemplo").first().click();
confere("abre a janela do projeto com a tarefa dele", await pg.locator("#dlg-projeto").evaluate((d) => d.open) && (await txt("#dlg-projeto")).includes("Tarefa atrasada"));
await pg.locator("#dlg-projeto [data-fechar]").first().click();
await pg.click("[data-visao='lixeira']"); confere("abre a lixeira", await pg.locator("#visao-lixeira").isVisible());
await pg.click("[data-visao='config']"); confere("abre Configurações com usuários", (await txt("#visao-config")).includes("Bruno Silva"));
await pg.evaluate(() => import("./js/util.js").then((u) => u.aviso("teste de aviso")));
confere("aviso aparece", (await txt("#aviso")) === "teste de aviso");
await pg.click("[data-visao='tarefas']"); await pg.locator("[data-modo='quadro']").click();
const grav = () => pg.evaluate(() => window.__gravacoes);
const antes = (await grav()).length;
await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa avulsa" }).dragTo(pg.locator("#quadro-tarefas .coluna-lista[data-coluna='ct2']"));
await pg.waitForTimeout(300);
const g1 = (await grav()).slice(antes);
confere("arrastar com mouse grava a nova coluna", g1.some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].coluna_id === "ct2"));
confere("estado de arrasto é limpo", await pg.evaluate(() => import("./js/estado.js").then((m) => m.estado.arrastando === null && m.estado.pendente === false)));
await pg.locator("#quadro-tarefas .coluna-novo").first().click();
confere("botão Adicionar tarefa da coluna abre a janela", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
await pg.locator("#dlg-tarefa [data-fechar]").first().click();
const n2 = (await grav()).length;
await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa atrasada" }).locator("button").first().click(); await pg.waitForTimeout(200);
confere("botão de concluir no cartão grava a conclusão", (await grav()).slice(n2).some((x) => x[0] === "tarefas" && x[2] && "concluida_em" in x[2]));
await pg.click("[data-visao='projetos']");
await pg.locator("#quadro-projetos .cartao").first().focus(); await pg.keyboard.press("Enter");
confere("Enter no cartão abre o projeto", await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.keyboard.press("Escape"); await pg.waitForTimeout(100);
const contorno = () => pg.evaluate(() => getComputedStyle(document.querySelector("#quadro-projetos .cartao")).outlineStyle);
await pg.keyboard.press("Tab"); await pg.keyboard.press("Shift+Tab");
confere("pelo teclado, o cartão em foco ganha o contorno", await pg.evaluate(() => document.activeElement.classList.contains("cartao")) && (await contorno()) !== "none");
await pg.locator("#quadro-projetos .cartao").first().click(); await pg.locator("#dlg-projeto [data-fechar]").first().click(); await pg.waitForTimeout(100);
confere("depois de clicar e fechar, o cartão não fica contornado", (await contorno()) === "none");
confere("opcoesResponsavel removida", await pg.evaluate(() => import("./js/estado.js").then((m) => !("opcoesResponsavel" in m))));
// Etapa 3: janelas e listas de projetos e tarefas
const fechaJanelas = () => pg.evaluate(() => { for (const d of document.querySelectorAll("dialog[open]")) d.close(); });
await fechaJanelas(); await pg.click("[data-visao='tarefas']");
await pg.selectOption("#filtro-projeto", "avulsas"); await pg.locator("[data-modo='quadro']").click();
confere("filtro Somente avulsas esconde a tarefa de projeto", !(await txt("#quadro-tarefas")).includes("Tarefa atrasada") && (await txt("#quadro-tarefas")).includes("Tarefa avulsa"));
await pg.selectOption("#filtro-projeto", "todos");
await pg.locator("[data-modo='lista']").click();
confere("Lista por data mostra o grupo Atrasadas", /Atrasadas/i.test(await txt("#lista-tarefas")));
await pg.locator("#lista-tarefas button.abrir").first().click();
confere("Lista por data abre a tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
let n3 = (await grav()).length;
await pg.fill("#t-titulo", "Tarefa editada"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar tarefa grava o título novo", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].titulo === "Tarefa editada"));
confere("janela da tarefa fecha ao salvar", !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)));
await pg.click("#nova-tarefa");
confere("Nova tarefa abre janela vazia", (await txt("#t-janela")) === "Nova tarefa" && (await pg.inputValue("#t-titulo")) === "");
n3 = (await grav()).length;
await pg.fill("#t-titulo", "Tarefa nova"); await pg.fill("#t-prazo", "2030-05-10"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("criar tarefa grava inserção", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "insert" && x[2].titulo === "Tarefa nova" && x[2].responsavel_id === "u1"));
await fechaJanelas(); await pg.locator("[data-modo='lista']").click(); await pg.locator("#lista-tarefas button.abrir").first().click();
n3 = (await grav()).length; await pg.click("#t-concluir"); await pg.waitForTimeout(200);
confere("concluir pela janela grava a conclusão", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[2] && x[2].concluida_em));
await pg.locator("[data-modo='concluidas']").click();
confere("Concluídas no modelo da Lista: nome, projeto e etiquetas com a data da conclusão", await pg.locator("#lista-concluidas .linha-tarefa").first().evaluate((l) => l.querySelector(".abrir .nome") && l.querySelector(".abrir .origem") && /Prioridade .* Concluída em \d+ [a-z]{3}/.test(l.querySelector(".chips").innerText.replace(/\s+/g, " ")) && !!l.querySelector(".marcar.feita")) && (await pg.locator("#concluidas-tarefas table").count()) === 0);
confere("Concluídas: responsável à direita e nome longo com reticências", (await pg.locator("#lista-concluidas .linha-tarefa .chips .avatar").count()) === 0 && (await primeiraLinha("#lista-concluidas .linha-tarefa", ".nome")).reticencias);
await pg.locator("#lista-concluidas .abrir").first().click();
confere("Concluídas abre a tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
await pg.locator("#dlg-tarefa [data-fechar]").first().click();
await pg.fill("#busca-concluidas", "zzz");
confere("busca em Concluídas responde", /Nenhuma tarefa concluída/.test(await txt("#concluidas-tarefas")));
await pg.click("[data-visao='projetos']"); await pg.getByText("Projeto Exemplo").first().click();
confere("janela do projeto mostra o histórico e o convite fixo da equipe", (await txt("#p-membros-resumo")) === "Clique para escolher" && /Criado por Ana Teste/.test(await txt("#p-historico")));
const alturaAntes = await pg.locator("#form-projeto").evaluate((f) => f.getBoundingClientRect().height); const topoAntes = await pg.locator("#p-membros-nota").evaluate((n) => n.getBoundingClientRect().top - n.closest("form").getBoundingClientRect().top);
await pg.click("#p-membros-resumo");
confere("lista de quem pode ver abre por cima, sem empurrar o conteúdo", await pg.locator("#p-seletor").evaluate((d) => d.open) && await pg.locator("#p-membros").isVisible() && Math.abs((await pg.locator("#p-membros-nota").evaluate((n) => n.getBoundingClientRect().top - n.closest("form").getBoundingClientRect().top)) - topoAntes) < 1 && Math.abs((await pg.locator("#form-projeto").evaluate((f) => f.getBoundingClientRect().height)) - alturaAntes) < 1);
confere("lista de pessoas tem altura limitada e rola", await pg.locator("#p-membros").evaluate((l) => getComputedStyle(l).overflowY === "auto" && l.getBoundingClientRect().height <= 180));
const ordem = () => pg.locator("#p-membros label").allInnerTexts().then((l) => l.map((x) => x.trim()).join(" | "));
confere("selecionados no topo da lista, depois do responsável", (await ordem()) === "Ana Teste (responsável) | Bruno Silva | Abel Costa");
confere("a pessoa da equipe vem marcada na lista", await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").isChecked());
await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").uncheck();
confere("marcar ou desmarcar não muda o texto do campo", (await txt("#p-membros-resumo")) === "Clique para escolher");
await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").check();
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").check(); await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").uncheck();
confere("a lista não muda de ordem enquanto a pessoa marca", (await ordem()) === "Ana Teste (responsável) | Bruno Silva | Abel Costa");
await pg.click("#p-membros-resumo"); await pg.click("#p-membros-resumo"); await pg.waitForTimeout(150);
confere("ao abrir de novo, os selecionados sobem para o topo", (await ordem()) === "Ana Teste (responsável) | Abel Costa | Bruno Silva");
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").uncheck(); await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").check();
await pg.keyboard.press("Escape");
confere("Esc fecha só a lista, não a janela do projeto", !(await pg.locator("#p-seletor").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.click("#p-membros-resumo"); await pg.click("#p-titulo");
confere("clicar fora fecha a lista", !(await pg.locator("#p-seletor").evaluate((d) => d.open)));
await pg.click("#p-membros-resumo"); await pg.fill("#p-membros-busca", "abel");
confere("Buscar pessoa filtra a lista", await pg.locator("#p-membros label", { hasText: "Abel Costa" }).isVisible() && !(await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).isVisible()));
await pg.fill("#p-membros-busca", "");
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").check(); await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").uncheck();
n3 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
const equipe = (await grav()).slice(n3).filter((x) => x[0] === "projeto_membros");
confere("salvar grava a pessoa incluída na equipe", equipe.some((x) => x[1] === "insert" && x[2].length === 1 && x[2][0].projeto_id === "p1" && x[2][0].usuario_id === "u3"));
confere("salvar retira da equipe só a pessoa desmarcada", equipe.some((x) => x[1] === "delete" && x[2].projeto_id === "p1" && x[2].usuario_id.join() === "u2"));
await pg.getByText("Projeto Exemplo").first().click();
n3 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar sem mexer na equipe não grava nada nela", !(await grav()).slice(n3).some((x) => x[0] === "projeto_membros"));
await pg.getByText("Projeto Exemplo").first().click();
await pg.locator("#p-lista li button:not(.marcar)").first().click();
confere("tarefa dentro do projeto abre por cima, sem fechar o projeto", await pg.locator("#dlg-tarefa").evaluate((d) => d.open) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click(); await pg.click("#p-adicionar");
confere("Adicionar tarefa no projeto já vem com o projeto", (await pg.inputValue("#t-projeto")) === "p1");
await pg.locator("#dlg-tarefa [data-fechar]").last().click();
confere("cancelar a tarefa volta para o projeto aberto", !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.fill("#p-descricao", "Texto ainda não salvo"); await pg.click("#p-adicionar");
n3 = (await grav()).length; await pg.fill("#t-titulo", "Tarefa pelo projeto"); await pg.fill("#t-prazo", "2030-06-10"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar a tarefa grava no projeto e volta para ele", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "insert" && x[2].projeto_id === "p1") && !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
confere("a descrição digitada no projeto não se perde", (await pg.inputValue("#p-descricao")) === "Texto ainda não salvo");
n3 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("depois da tarefa, salvar o projeto grava a descrição", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].descricao === "Texto ainda não salvo"));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click();
n3 = (await grav()).length; await pg.fill("#p-titulo", "Projeto editado"); await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar projeto grava o título novo", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].titulo === "Projeto editado"));
await pg.click("#novo-projeto");
confere("Novo projeto abre janela vazia", (await txt("#p-janela")) === "Novo projeto");
n3 = (await grav()).length; await pg.fill("#p-titulo", "Projeto novo"); await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("criar projeto grava inserção", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "insert" && x[2].titulo === "Projeto novo"));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click(); await pg.click("#p-excluir");
confere("excluir projeto pede confirmação", await pg.locator("#dlg-confirma").evaluate((d) => d.open));
n3 = (await grav()).length; await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("confirmar exclusão manda para a lixeira", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[2] && x[2].arquivado_em));
await fechaJanelas();
// Etapa 4: lixeiras, Configurações e convites
await pg.reload(); await pg.waitForSelector("#app:not([hidden])");
await pg.click("[data-visao='lixeira']");
confere("minha lixeira lista os itens excluídos", (await txt("#tabela-minha-lixeira")).includes("Tarefa excluída") && /Tarefa avulsa/.test(await txt("#tabela-minha-lixeira")));
n3 = (await grav()).length; await pg.locator("#tabela-minha-lixeira button", { hasText: "Restaurar" }).first().click(); await pg.waitForTimeout(200);
confere("Restaurar na minha lixeira chama restaurar_item", (await grav()).slice(n3).some((x) => x[0] === "rpc" && x[1] === "restaurar_item" && x[2].tabela === "tarefas"));
await pg.click("[data-visao='config']");
confere("Configurações lista usuários e colunas", (await txt("#tabela-usuarios")).includes("Ana Teste (você)") && (await txt("#tabela-colunas-tarefas")).includes("A fazer"));
confere("lixeira geral mostra só tarefa de projeto", (await txt("#tabela-lixeira")).includes("Tarefa de projeto excluída") && !(await txt("#tabela-lixeira")).includes("Tarefa excluída\n"));
n3 = (await grav()).length; await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).getByRole("button", { name: "Bloquear" }).click(); await pg.waitForTimeout(200);
confere("Bloquear usuário grava ativo = false", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].ativo === false));
n3 = (await grav()).length; await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).locator("select").selectOption("admin"); await pg.waitForTimeout(200);
confere("trocar tipo de usuário grava o papel", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].papel === "admin"));
n3 = (await grav()).length; await pg.locator("#tabela-colunas-tarefas tr", { hasText: "A fazer" }).getByRole("button", { name: "Descer" }).click(); await pg.waitForTimeout(200);
confere("Descer coluna grava a nova ordem", (await grav()).slice(n3).some((x) => x[0] === "colunas" && x[2] && "ordem" in x[2]));
await pg.locator("#tabela-colunas-projetos tr", { hasText: "Concluído" }).getByRole("button", { name: "Editar" }).click();
confere("Editar coluna abre a janela preenchida", (await pg.inputValue("#c-nome")) === "Concluído" && await pg.isChecked("#c-concluida"));
n3 = (await grav()).length; await pg.fill("#c-nome", "Feito"); await pg.locator("#form-coluna [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar coluna grava o nome", (await grav()).slice(n3).some((x) => x[0] === "colunas" && x[1] === "update" && x[2].nome === "Feito"));
await pg.locator("[data-nova-coluna]").first().click();
confere("Nova coluna abre a janela vazia", (await txt("#c-janela")) === "Nova coluna" && (await pg.inputValue("#c-nome")) === "");
await fechaJanelas();
await pg.locator("#tabela-colunas-tarefas tr", { hasText: "A fazer" }).getByRole("button", { name: "Excluir" }).click();
confere("excluir coluna com cartões avisa e não apaga", /ainda tem \d+ cart/.test(await txt("#aviso")));
n3 = (await grav()).length; await pg.locator("#tabela-lixeira").getByRole("button", { name: "Excluir de vez" }).first().click();
confere("Excluir de vez pede confirmação", await pg.locator("#dlg-confirma").evaluate((d) => d.open));
await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("confirmar apaga do banco", (await grav()).slice(n3).some((x) => x[1] === "delete"));
n3 = (await grav()).length; await pg.locator("#tabela-lixeira").getByRole("button", { name: "Restaurar" }).first().click(); await pg.waitForTimeout(200);
confere("Restaurar na lixeira geral chama restaurar_item", (await grav()).slice(n3).some((x) => x[0] === "rpc"));
await pg.click("#convidar");
confere("Convidar abre a janela", await pg.locator("#dlg-convite").evaluate((d) => d.open));
await pg.fill("#v-nome", "Carla"); await pg.fill("#v-email", "carla@exemplo.com"); n3 = (await grav()).length; await pg.click("#v-gerar"); await pg.waitForTimeout(300);
confere("gerar convite chama a função e mostra o link", (await grav()).slice(n3).some((x) => x[0] === "funcao" && x[2].acao === "convidar") && /\?convite=tok123&tipo=invite$/.test(await pg.inputValue("#v-link")));
await fechaJanelas(); n3 = (await grav()).length;
await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).getByRole("button", { name: "Gerar novo link" }).click(); await pg.waitForTimeout(300);
confere("Gerar novo link mostra link de nova senha", (await grav()).slice(n3).some((x) => x[0] === "funcao" && x[2].acao === "novo_link") && /tipo=recovery$/.test(await pg.inputValue("#v-link")));
await fechaJanelas();
await pg.click("#btn-conta");
confere("Minha conta abre com o nome", (await pg.inputValue("#m-nome")) === "Ana Teste");
n3 = (await grav()).length; await pg.fill("#m-nome", "Ana T."); await pg.locator("#form-conta [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar Minha conta grava o nome", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].nome === "Ana T."));
await pg.goto("http://localhost:8123/?convite=abc"); await pg.waitForSelector("#tela-senha:not([hidden])");
confere("link de convite abre a tela de criar senha", (await txt("#senha-titulo")) === "Crie a sua senha");
// Celular: moldura fixa, barra de baixo e painel "Mais"
await pg.setViewportSize({ width: 390, height: 844 }); await pg.goto("http://localhost:8123/"); await pg.waitForSelector("#app:not([hidden])");
confere("celular: a página não rola nem para os lados nem para baixo", await pg.evaluate(() => document.documentElement.scrollWidth === innerWidth && document.documentElement.scrollHeight === innerHeight));
const caixa = await pg.locator(".menu").boundingBox();
confere("celular: barra de baixo encostada no rodapé, com três itens", Math.round(caixa.y + caixa.height) === 844 && (await pg.locator(".menu button:visible").count()) === 3);
// Celular: quadro com uma coluna por vez
const colunaVisivel = (q) => pg.locator(`#quadro-${q} .coluna:visible`).evaluateAll((l) => l.map((c) => c.dataset.coluna).join());
confere("celular: o quadro mostra uma coluna por vez, a primeira", (await colunaVisivel("projetos")) === "cp1");
confere("celular: etiquetas com o nome e a contagem de cada coluna", (await pg.locator("#quadro-projetos .etiquetas button").allInnerTexts()).map((x) => x.replace(/\s+/g, " ").trim()).join("|") === "A fazer 1|Concluído 0");
confere("celular: frase de como mudar de coluna", (await txt("#quadro-projetos .dica-coluna")) === "Para mudar de coluna, abra o projeto.");
confere("celular: o quadro não rola para os lados e o cartão ocupa a largura", await pg.locator("#quadro-projetos").evaluate((q) => getComputedStyle(q).overflowX === "visible" && q.querySelector(".cartao").getBoundingClientRect().width > 340));
confere("celular: o cartão não é arrastável", await pg.locator("#quadro-projetos .cartao").first().evaluate((c) => c.draggable === false));
await pg.locator("#quadro-projetos .etiquetas button", { hasText: "Concluído" }).click();
confere("celular: tocar na etiqueta troca a coluna", (await colunaVisivel("projetos")) === "cp2" && (await pg.locator("#quadro-projetos .etiquetas [aria-selected='true']").innerText()).includes("Concluído"));
await pg.click("[data-visao='tarefas']"); await pg.locator("[data-modo='quadro']").click();
confere("celular: cada quadro tem a sua coluna (Tarefas segue na primeira)", (await colunaVisivel("tarefas")) === "ct1" && (await txt("#quadro-tarefas .dica-coluna")) === "Para mudar de coluna, abra a tarefa.");
await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); await pg.click("[data-visao='projetos']");
confere("celular: ao voltar, o quadro mostra a última coluna em que a pessoa esteve", (await colunaVisivel("projetos")) === "cp2");
await pg.evaluate(() => localStorage.setItem("gp-coluna-projetos", "coluna-que-sumiu")); await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); await pg.click("[data-visao='projetos']");
confere("celular: se a coluna guardada não existe mais, mostra a primeira", (await colunaVisivel("projetos")) === "cp1");
await pg.locator("#quadro-projetos .cartao").first().click(); await pg.selectOption("#p-coluna", "cp2");
let n5 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("celular: mudar de coluna pelo campo Coluna da janela grava a nova coluna", (await grav()).slice(n5).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].coluna_id === "cp2"));
// Celular: botão "+", painel "Novo" e cabeçalho enxuto
confere("celular: botão + no lugar do botão do topo", await pg.locator("#botao-novo").isVisible() && !(await pg.locator("#novo-projeto").isVisible()));
confere("celular: botão + dentro da moldura, acima da barra de baixo", await pg.evaluate(() => { const b = document.getElementById("botao-novo"), r = b.getBoundingClientRect(), m = document.querySelector(".menu").getBoundingClientRect(); return getComputedStyle(b).position !== "fixed" && r.bottom <= m.top && r.right <= innerWidth && b.parentElement.id === "app"; }));
await pg.click("#botao-novo");
confere("celular: + abre o painel Novo com as duas opções", await pg.locator("#dlg-novo").evaluate((d) => d.open) && await pg.locator("#novo-item-tarefa").isVisible() && await pg.locator("#novo-item-projeto").isVisible());
await pg.click("#novo-item-projeto");
confere("celular: Novo projeto pelo painel abre a janela vazia e fecha o painel", (await txt("#p-janela")) === "Novo projeto" && await pg.locator("#dlg-projeto").evaluate((d) => d.open) && !(await pg.locator("#dlg-novo").evaluate((d) => d.open)));
await pg.locator("#dlg-projeto [data-fechar]").first().click();
await pg.click(".menu [data-visao='tarefas']");
confere("celular: Tarefas abre na Lista", (await pg.locator("[data-modo='lista']").getAttribute("aria-selected")) === "true" && await pg.locator("#lista-tarefas").isVisible() && !(await pg.locator("#quadro-tarefas").isVisible()));
confere("celular: na Lista, responsável na primeira linha, à direita, e nome longo com reticências", certo(await primeiraLinha("#lista-tarefas .linha-tarefa", ".nome")));
confere("celular: na Lista, as etiquetas ficam na linha de baixo, sem o responsável", await pg.locator("#lista-tarefas .linha-tarefa").first().evaluate((l) => l.querySelector(".chips").getBoundingClientRect().top >= l.querySelector(".abrir").getBoundingClientRect().bottom && !l.querySelector(".chips .avatar")));
confere("celular: alternância na ordem Lista, Quadro, Concluídas, na largura da tela", await pg.evaluate(() => { const x = (m) => document.querySelector(`[data-modo='${m}']`).getBoundingClientRect().left; const a = document.querySelector(".abas").getBoundingClientRect(); return x("lista") < x("quadro") && x("quadro") < x("concluidas") && a.width > 340 && document.querySelector("[data-modo='lista']").innerText.trim() === "Lista"; }));
confere("celular: filtro de projeto na largura da tela, sem o botão Nova tarefa", (await pg.locator("#filtro-projeto").evaluate((s) => s.getBoundingClientRect().width)) > 340 && !(await pg.locator("#nova-tarefa").isVisible()));
await pg.click("#botao-novo"); await pg.click("#novo-item-tarefa");
confere("celular: Nova tarefa pelo painel abre a janela vazia", (await txt("#t-janela")) === "Nova tarefa" && (await pg.inputValue("#t-titulo")) === "" && !(await pg.locator("#dlg-novo").evaluate((d) => d.open)));
await pg.locator("#dlg-tarefa [data-fechar]").first().click();
await pg.click("#menu-mais"); await pg.click("#dlg-mais [data-visao='lixeira']");
confere("celular: na Lixeira não há botão +", !(await pg.locator("#botao-novo").isVisible()));
await pg.click(".menu [data-visao='projetos']");
await pg.evaluate(() => localStorage.clear());
await pg.click("[data-visao='tarefas']"); await pg.locator("[data-modo='quadro']").click();
confere("celular: trocar de tela pela barra de baixo", await pg.locator("#visao-tarefas").isVisible() && (await pg.evaluate(() => document.documentElement.scrollWidth === innerWidth)));
await pg.click("#menu-mais");
confere("celular: Mais abre o painel com Configurações para o admin", await pg.locator("#dlg-mais").evaluate((d) => d.open) && await pg.locator("#mais-config").isVisible());
await pg.click("#dlg-mais [data-visao='lixeira']");
confere("celular: Lixeira pelo painel Mais abre a tela e fecha o painel", await pg.locator("#visao-lixeira").isVisible() && !(await pg.locator("#dlg-mais").evaluate((d) => d.open)));
await pg.click("#menu-mais"); await pg.click("#mais-conta");
confere("celular: Minha conta pelo painel Mais", await pg.locator("#dlg-conta").evaluate((d) => d.open) && !(await pg.locator("#dlg-mais").evaluate((d) => d.open)));
confere("celular: campos com letra de 16 px, para o iPhone não ampliar a tela", await pg.evaluate(() => [...document.querySelectorAll("input:not([type=checkbox]), select, textarea")].every((c) => parseFloat(getComputedStyle(c).fontSize) >= 16)));
await pg.keyboard.press("Escape"); await pg.click(".menu [data-visao='tarefas']"); await pg.locator("[data-modo='lista']").click(); await pg.locator("#lista-tarefas .abrir").first().click();
confere("celular: o campo de data tem a mesma largura dos outros campos", await pg.evaluate(() => { const l = (id) => Math.round(document.getElementById(id).getBoundingClientRect().width); return l("t-prazo") === l("t-titulo") && l("t-prazo") === l("t-responsavel"); }));
await pg.locator("#dlg-tarefa [data-fechar]").first().click();
confere("sem #diag, a caixa de diagnóstico não existe", (await pg.locator("#diagnostico").count()) === 0);
await pg.goto("http://localhost:8123/#diag"); await pg.reload(); await pg.waitForSelector("#diagnostico");
confere("com #diag, a caixa de diagnóstico mostra as medidas", /janela \(inner\)\s+390 x 844/.test(await txt("#diagnostico")) && /barra de baixo\s+topo/.test(await txt("#diagnostico")));
// Versão do site e atualização de páginas já abertas
const versaoNoArquivo = fs.readFileSync(path.join(raiz, "js/versao.js"), "utf8").match(/VERSAO = "(\d{4}\.\d{2}\.\d{2}-\d+)"/)?.[1];
confere("versao.js traz a versão no formato ano.mês.dia-ordem", !!versaoNoArquivo);
confere("com #diag, a caixa mostra a versão do site", (await txt("#diagnostico")).includes("versão do site      " + versaoNoArquivo));
await pg.goto("http://localhost:8123/"); await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(300);
confere("com a mesma versão publicada, a página não avisa nem recarrega", (await pg.locator("#aviso-versao").count()) === 0 && (await pg.evaluate(() => sessionStorage.getItem("gp-atualizou-para"))) === null);
await pg.click("#menu-mais"); await pg.click("#mais-conta");
confere("Minha conta mostra a versão do site", (await txt("#versao-do-site")) === "Versão do site: " + versaoNoArquivo);
// Daqui em diante o servidor "publica" outra versão: só a consulta de versão (com ?t=) recebe o arquivo novo
await pg.route(/\/js\/versao\.js\?t=/, (r) => r.fulfill({ contentType: "text/javascript", body: 'export const VERSAO = "2099.01.01-1";' }));
const confereVersao = () => pg.evaluate(() => import("./js/atualizacao.js").then((m) => m.conferirVersao(true)));
let cargas = 0; pg.on("load", () => cargas++);
await confereVersao(); await pg.waitForTimeout(300);
confere("versão nova com janela aberta: avisa e não recarrega", (await pg.locator("#aviso-versao").count()) === 1 && cargas === 0 && await pg.locator("#dlg-conta").evaluate((d) => d.open));
await pg.locator("#dlg-conta [data-fechar]").first().click(); await pg.waitForEvent("load"); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(400);
confere("ao fechar a janela, a página se atualiza sozinha, uma vez", cargas === 1 && (await pg.evaluate(() => sessionStorage.getItem("gp-atualizou-para"))) === "2099.01.01-1");
confere("se a recarga não trouxe a versão nova, fica o aviso, sem recarregar em laço", (await pg.locator("#aviso-versao").isVisible()) && (await txt("#aviso-versao")).includes("Há uma versão nova do site.") && cargas === 1);
await pg.locator("#aviso-versao button").click(); await pg.waitForEvent("load"); await pg.waitForSelector("#app:not([hidden])");
confere("o botão Atualizar do aviso recarrega a página", cargas === 2);
await pg.evaluate(() => sessionStorage.clear()); cargas = 0;
await pg.reload(); await pg.waitForEvent("load"); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(400);
confere("versão nova com a pessoa livre: atualiza sozinha ao abrir, sem aviso antes", cargas === 2 && (await pg.evaluate(() => sessionStorage.getItem("gp-atualizou-para"))) === "2099.01.01-1");
await pg.unroute(/\/js\/versao\.js\?t=/);
confere("nenhum erro no console", erros.length === 0); erros.forEach((e) => console.log("   " + e));
console.log(`RESULTADO: ${ok} ok, ${falhas} falhas`); await b.close(); srv.close();
process.exit(falhas ? 1 : 0);
