// Teste de tela do site de Gestão de Projetos, em navegador automatizado.
// Usa dados de exemplo (supabase-de-mentira.js) e não toca no banco real. Como rodar: ver README.md desta pasta.
import { createRequire } from "module"; import { fileURLToPath } from "url"; import http from "http"; import fs from "fs"; import path from "path";
const aqui = path.dirname(fileURLToPath(import.meta.url));
const raiz = process.env.SITE || path.join(aqui, "..");   // pasta onde está o index.html
let chromium;
try { ({ chromium } = await import("playwright")); }
catch (_) { ({ chromium } = createRequire((process.env.NODE_PATH || ".") + "/")("playwright")); }
const tipos = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".svg": "image/svg+xml", ".png": "image/png" };
const srv = http.createServer((rq, rs) => { const f = path.join(raiz, rq.url.split("?")[0].replace(/\/$/, "/index.html"));
  fs.readFile(f, (e, d) => { if (e) { rs.writeHead(404); rs.end(); } else { rs.writeHead(200, { "content-type": tipos[path.extname(f)] || "application/octet-stream" }); rs.end(d); } }); }).listen(8123);
const b = await chromium.launch(); const pg = await b.newPage(); const erros = [];
pg.on("pageerror", (e) => erros.push("erro: " + e.message)); pg.on("console", (m) => { if (m.type() === "error" && !/404|Failed to load resource/.test(m.text())) erros.push("console: " + m.text()); });
await pg.route("**/*", (r) => { const u = r.request().url();
  if (u.includes("supabase-js")) return r.fulfill({ contentType: "text/javascript", body: fs.readFileSync(path.join(aqui, "supabase-de-mentira.js"), "utf8") });
  if (u.startsWith("http://localhost:8123")) return r.continue(); return r.abort(); });
let ok = 0, falhas = 0; const confere = (nome, cond) => { cond ? ok++ : falhas++; console.log((cond ? "ok    " : "FALHA ") + nome); };
await pg.goto("http://localhost:8123/"); await pg.waitForSelector("#app:not([hidden])", { timeout: 8000 });
const txt = async (s) => (await pg.locator(s).innerText());
confere("entra e mostra o app", await pg.locator("#app").isVisible());
confere("nome e papel na conta", (await txt("#conta-nome")) === "Ana Teste" && (await txt("#conta-papel")) === "Administrador");
confere("avatar com iniciais", (await txt("#conta-avatar")) === "AT");
confere("iniciais ignoram parênteses no nome", (await pg.evaluate(() => import("./js/estado.js").then((m) => { m.estado.perfis.push({ id: "zz", nome: "Gauten (Admin)" }); const t = m.avatar("zz").textContent; m.estado.perfis.pop(); return t; }))) === "GA");
confere("menu Configurações visível para admin", await pg.locator("#menu-config").isVisible());
confere("quadro de projetos mostra o cartão", (await txt("#visao-projetos")).includes("Projeto Exemplo"));
confere("colunas do quadro", /A FAZER/i.test(await txt("#visao-projetos")) && /CONCLUÍDO/i.test(await txt("#visao-projetos")));
confere("computador: colunas lado a lado, sem etiquetas nem frase do celular", (await pg.locator("#quadro-projetos .coluna:visible").count()) === 2 && !(await pg.locator("#quadro-projetos .etiquetas").isVisible()) && !(await pg.locator("#quadro-projetos .dica-coluna").isVisible()));
confere("cartão de projeto no modelo da tarefa: nome com o responsável, etiquetas e andamento, nessa ordem", (await pg.locator("#quadro-projetos .cartao").first().evaluate((c) => [...c.children].map((x) => x.className).join("|"))) === "topo-projeto|chips|rodape" && (await pg.locator("#quadro-projetos .cartao .chips").first().innerText()).replace(/\s+/g, " ").trim() === "Prioridade alta 2 pessoas 1 jan 2020" && (await pg.locator("#quadro-projetos .cartao .chips .avatar, #quadro-projetos .cartao .rodape .avatar").count()) === 0);
confere("cartão do projeto mostra o progresso por extenso", (await txt("#quadro-projetos .progresso")).includes("0 de 1 tarefa"));
confere("resumo de projetos no cabeçalho", (await txt("#resumo-projetos")) === "1 projeto · 1 atrasado");
await pg.click("[data-visao='tarefas']");
confere("computador: Tarefas abre no Quadro, sem o botão + do celular", (await pg.locator("[data-modo='quadro']").getAttribute("aria-selected")) === "true" && (await txt("[data-modo='lista']")) === "Lista por data" && !(await pg.locator("#botao-novo").isVisible()) && await pg.locator("#nova-tarefa").isVisible());
confere("resumo de tarefas no cabeçalho", (await txt("#resumo-tarefas")) === "2 tarefas abertas · 1 atrasada");
confere("quadro de tarefas sem texto solto antes das colunas", await pg.locator("#quadro-tarefas").evaluate((q) => [...q.childNodes].every((n) => n.nodeType === 1)));
confere("quadro de tarefas mostra as duas tarefas", (await txt("#visao-tarefas")).includes("Tarefa atrasada") && (await txt("#visao-tarefas")).includes("Tarefa avulsa"));
confere("data curta no cartão (1 jan 2020)", /1 jan 2020/.test(await txt("#visao-tarefas")));
confere("cartão de tarefa no modelo da Lista: nome, projeto e etiquetas, nessa ordem", (await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa atrasada" }).evaluate((c) => [...c.children].map((x) => x.className).join("|"))) === "topo-tarefa|origem|chips");
confere("cartão de tarefa e Lista usam as mesmas etiquetas", (await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa atrasada" }).locator(".chips").innerText()).replace(/\s+/g, " ").trim() === "Prioridade média 1 jan 2020");
// O responsável fica na primeira linha, à direita; o nome longo termina em reticências, com folga antes do ícone
const primeiraLinha = (sel, nomeSel) => pg.locator(sel).first().evaluate((c, nomeSel) => { const a = c.querySelector(".avatar"), n = c.querySelector(nomeSel); n.textContent = "Um nome de tarefa comprido o bastante para não caber em uma linha só do cartão ou da lista, de propósito";
  const ra = a.getBoundingClientRect(), rn = n.getBoundingClientRect(), rc = c.getBoundingClientRect();
  return { naLinhaDoNome: ra.top < rn.bottom && ra.bottom > rn.top, aDireita: rc.right - ra.right < 24, folga: ra.left - rn.right, reticencias: getComputedStyle(n).textOverflow === "ellipsis" && n.scrollWidth > n.clientWidth && rn.height < 30 }; }, nomeSel);
const certo = (m) => m.naLinhaDoNome && m.aDireita && m.folga >= 10 && m.reticencias;
await pg.click("[data-visao='projetos']");
confere("cartão de projeto: responsável na primeira linha, à direita, e nome longo com reticências", certo(await primeiraLinha("#quadro-projetos .cartao", ".nome")));
await pg.click("[data-visao='tarefas']");
confere("cartão de tarefa: responsável na primeira linha, à direita, e nome longo com reticências", certo(await primeiraLinha("#quadro-tarefas .cartao", ".nome")));
for (const modo of await pg.locator("[data-modo]").all()) { await modo.click(); }
confere("troca de modos de tarefas sem erro", erros.length === 0);
await pg.locator("[data-modo='lista']").click();
confere("lista por data mostra a coluna de cada tarefa", (await pg.locator("#lista-tarefas .linha-tarefa .chip[title='Coluna no quadro']").count()) === 2);
await pg.locator("[data-modo='quadro']").click();
await pg.getByText("Tarefa avulsa").first().click();
confere("abre a janela da tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
const abertaPC = (id) => pg.locator(id).evaluate((d) => d.open);
await pg.mouse.click(720, 450); await pg.waitForTimeout(100);
confere("computador: clicar dentro da janela da tarefa não fecha", await abertaPC("#dlg-tarefa"));
await pg.mouse.move(720, 300); await pg.mouse.down(); await pg.mouse.move(20, 20); await pg.mouse.up(); await pg.waitForTimeout(100);
confere("computador: arrastar o mouse de dentro para fora não fecha a janela", await abertaPC("#dlg-tarefa"));
await pg.fill("#t-descricao", "Em andamento"); await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("computador: com algo digitado, clicar fora não fecha a janela da tarefa", await abertaPC("#dlg-tarefa") && (await pg.inputValue("#t-descricao")) === "Em andamento");
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click(); await pg.getByText("Tarefa avulsa").first().click();
await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("computador: sem alteração, clicar fora fecha a janela da tarefa", !(await abertaPC("#dlg-tarefa")));
await pg.getByText("Tarefa avulsa").first().click();
confere("computador: a tarefa abre direto no formulário, sem a leitura do celular", await pg.locator("#form-tarefa").isVisible() && !(await pg.locator("#t-leitura").isVisible()) && await pg.locator("#dlg-tarefa").evaluate((d) => getComputedStyle(d, "::before").content === "none"));
confere("histórico na janela", /Criado por Ana Teste em \d\d\/\d\d\/\d{4} às \d\d:\d\d/.test(await txt("#dlg-tarefa")));
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click();
await pg.click("[data-visao='projetos']"); await pg.getByText("Projeto Exemplo").first().click();
confere("abre a janela do projeto com a tarefa dele", await pg.locator("#dlg-projeto").evaluate((d) => d.open) && (await txt("#dlg-projeto")).includes("Tarefa atrasada"));
confere("computador: o projeto abre direto no formulário, sem a leitura do celular", await pg.locator("#form-projeto").isVisible() && !(await pg.locator("#p-leitura").isVisible()));
await pg.locator("#p-lista li button:not(.marcar)").first().click(); await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("computador: com a tarefa aberta por cima do projeto, clicar fora fecha só a tarefa", !(await abertaPC("#dlg-tarefa")) && await abertaPC("#dlg-projeto"));
await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("computador: clicar fora fecha a janela do projeto sem alteração", !(await abertaPC("#dlg-projeto")));
await pg.click("#btn-conta"); await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("computador: clicar fora fecha Minha conta", !(await abertaPC("#dlg-conta")));
await pg.click("[data-visao='lixeira']"); confere("abre a lixeira", await pg.locator("#visao-lixeira").isVisible());
await pg.click("[data-visao='config']"); confere("abre Configurações com usuários", (await txt("#visao-config")).includes("Bruno Silva"));
await pg.evaluate(() => import("./js/util.js").then((u) => u.aviso("teste de aviso")));
confere("aviso aparece", (await txt("#aviso")) === "teste de aviso");
await pg.click("[data-visao='tarefas']"); await pg.locator("[data-modo='quadro']").click();
const grav = () => pg.evaluate(() => window.__gravacoes);
const antes = (await grav()).length;
await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa avulsa" }).dragTo(pg.locator("#quadro-tarefas .coluna-lista[data-coluna='ct2']"));
await pg.waitForTimeout(300);
const g1 = (await grav()).slice(antes);
confere("arrastar com mouse grava a nova coluna", g1.some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].coluna_id === "ct2"));
confere("estado de arrasto é limpo", await pg.evaluate(() => import("./js/estado.js").then((m) => m.estado.arrastando === null && m.estado.pendente === false)));
await pg.locator("#quadro-tarefas .coluna-novo").first().click();
confere("botão Adicionar tarefa da coluna abre a janela", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click();
const n2 = (await grav()).length;
await pg.locator("#quadro-tarefas .cartao", { hasText: "Tarefa atrasada" }).locator("button").first().click(); await pg.waitForTimeout(200);
confere("botão de concluir no cartão grava a conclusão", (await grav()).slice(n2).some((x) => x[0] === "tarefas" && x[2] && "concluida_em" in x[2]));
await pg.click("[data-visao='projetos']");
await pg.locator("#quadro-projetos .cartao").first().focus(); await pg.keyboard.press("Enter");
confere("Enter no cartão abre o projeto", await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.keyboard.press("Escape"); await pg.waitForTimeout(100);
const contorno = () => pg.evaluate(() => getComputedStyle(document.querySelector("#quadro-projetos .cartao")).outlineStyle);
await pg.keyboard.press("Tab"); await pg.keyboard.press("Shift+Tab");
confere("pelo teclado, o cartão em foco ganha o contorno", await pg.evaluate(() => document.activeElement.classList.contains("cartao")) && (await contorno()) !== "none");
await pg.locator("#quadro-projetos .cartao").first().click(); await pg.locator("#dlg-projeto [data-fechar]:visible").first().click(); await pg.waitForTimeout(100);
confere("depois de clicar e fechar, o cartão não fica contornado", (await contorno()) === "none");
confere("opcoesResponsavel removida", await pg.evaluate(() => import("./js/estado.js").then((m) => !("opcoesResponsavel" in m))));
// Etapa 3: janelas e listas de projetos e tarefas
const fechaJanelas = () => pg.evaluate(() => { for (const d of document.querySelectorAll("dialog[open]")) d.close(); });
await fechaJanelas(); await pg.click("[data-visao='tarefas']");
await pg.selectOption("#filtro-projeto", "avulsas"); await pg.locator("[data-modo='quadro']").click();
confere("filtro Somente avulsas esconde a tarefa de projeto", !(await txt("#quadro-tarefas")).includes("Tarefa atrasada") && (await txt("#quadro-tarefas")).includes("Tarefa avulsa"));
await pg.selectOption("#filtro-projeto", "todos");
await pg.locator("[data-modo='lista']").click();
confere("Lista por data mostra o grupo Atrasadas", /Atrasadas/i.test(await txt("#lista-tarefas")));
await pg.locator("#lista-tarefas button.abrir").first().click();
confere("Lista por data abre a tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
let n3 = (await grav()).length;
await pg.fill("#t-titulo", "Tarefa editada"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar tarefa grava o título novo", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].titulo === "Tarefa editada"));
confere("janela da tarefa fecha ao salvar", !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)));
await pg.click("#nova-tarefa");
confere("Nova tarefa abre janela vazia", (await txt("#t-janela")) === "Nova tarefa" && (await pg.inputValue("#t-titulo")) === "");
n3 = (await grav()).length;
await pg.fill("#t-titulo", "Tarefa nova"); await pg.fill("#t-prazo", "2030-05-10"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("criar tarefa grava inserção", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "insert" && x[2].titulo === "Tarefa nova" && x[2].responsavel_id === "u1"));
await fechaJanelas(); await pg.locator("[data-modo='lista']").click(); await pg.locator("#lista-tarefas button.abrir").first().click();
n3 = (await grav()).length; await pg.click("#t-concluir"); await pg.waitForTimeout(200);
confere("concluir pela janela grava a conclusão", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[2] && x[2].concluida_em));
await pg.locator("[data-modo='concluidas']").click();
confere("Concluídas no modelo da Lista: nome, projeto e etiquetas com a data da conclusão", await pg.locator("#lista-concluidas .linha-tarefa").first().evaluate((l) => l.querySelector(".abrir .nome") && l.querySelector(".abrir .origem") && /Prioridade .* Concluída em \d+ [a-z]{3}/.test(l.querySelector(".chips").innerText.replace(/\s+/g, " ")) && !!l.querySelector(".marcar.feita")) && (await pg.locator("#concluidas-tarefas table").count()) === 0);
confere("Concluídas: responsável à direita e nome longo com reticências", (await pg.locator("#lista-concluidas .linha-tarefa .chips .avatar").count()) === 0 && (await primeiraLinha("#lista-concluidas .linha-tarefa", ".nome")).reticencias);
await pg.locator("#lista-concluidas .abrir").first().click();
confere("Concluídas abre a tarefa", await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click();
await pg.fill("#busca-concluidas", "zzz");
confere("busca em Concluídas responde", /Nenhuma tarefa concluída/.test(await txt("#concluidas-tarefas")));
await pg.click("[data-visao='projetos']"); await pg.getByText("Projeto Exemplo").first().click();
confere("janela do projeto mostra o histórico e o convite fixo da equipe", (await txt("#p-membros-resumo")) === "Clique para escolher" && /Criado por Ana Teste/.test(await txt("#p-historico")));
const alturaAntes = await pg.locator("#form-projeto").evaluate((f) => f.getBoundingClientRect().height); const topoAntes = await pg.locator("#p-membros-nota").evaluate((n) => n.getBoundingClientRect().top - n.closest("form").getBoundingClientRect().top);
await pg.click("#p-membros-resumo");
confere("lista de quem pode ver abre por cima, sem empurrar o conteúdo", await pg.locator("#p-seletor").evaluate((d) => d.open) && await pg.locator("#p-membros").isVisible() && Math.abs((await pg.locator("#p-membros-nota").evaluate((n) => n.getBoundingClientRect().top - n.closest("form").getBoundingClientRect().top)) - topoAntes) < 1 && Math.abs((await pg.locator("#form-projeto").evaluate((f) => f.getBoundingClientRect().height)) - alturaAntes) < 1);
confere("lista de pessoas tem altura limitada e rola", await pg.locator("#p-membros").evaluate((l) => getComputedStyle(l).overflowY === "auto" && l.getBoundingClientRect().height <= 180));
const ordem = () => pg.locator("#p-membros label").allInnerTexts().then((l) => l.map((x) => x.trim()).join(" | "));
confere("selecionados no topo da lista, depois do responsável", (await ordem()) === "Ana Teste (responsável) | Bruno Silva | Abel Costa");
confere("a pessoa da equipe vem marcada na lista", await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").isChecked());
await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").uncheck();
confere("marcar ou desmarcar não muda o texto do campo", (await txt("#p-membros-resumo")) === "Clique para escolher");
await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").check();
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").check(); await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").uncheck();
confere("a lista não muda de ordem enquanto a pessoa marca", (await ordem()) === "Ana Teste (responsável) | Bruno Silva | Abel Costa");
await pg.click("#p-membros-resumo"); await pg.click("#p-membros-resumo"); await pg.waitForTimeout(150);
confere("ao abrir de novo, os selecionados sobem para o topo", (await ordem()) === "Ana Teste (responsável) | Abel Costa | Bruno Silva");
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").uncheck(); await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").check();
await pg.keyboard.press("Escape");
confere("Esc fecha só a lista, não a janela do projeto", !(await pg.locator("#p-seletor").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.click("#p-membros-resumo"); await pg.click("#p-titulo");
confere("clicar fora fecha a lista", !(await pg.locator("#p-seletor").evaluate((d) => d.open)));
await pg.click("#p-membros-resumo"); await pg.fill("#p-membros-busca", "abel");
confere("Buscar pessoa filtra a lista", await pg.locator("#p-membros label", { hasText: "Abel Costa" }).isVisible() && !(await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).isVisible()));
await pg.fill("#p-membros-busca", "");
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").check(); await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").uncheck();
n3 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
const equipe = (await grav()).slice(n3).filter((x) => x[0] === "projeto_membros");
confere("salvar grava a pessoa incluída na equipe", equipe.some((x) => x[1] === "insert" && x[2].length === 1 && x[2][0].projeto_id === "p1" && x[2][0].usuario_id === "u3"));
confere("salvar retira da equipe só a pessoa desmarcada", equipe.some((x) => x[1] === "delete" && x[2].projeto_id === "p1" && x[2].usuario_id.join() === "u2"));
await pg.getByText("Projeto Exemplo").first().click();
n3 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar sem mexer na equipe não grava nada nela", !(await grav()).slice(n3).some((x) => x[0] === "projeto_membros"));
await pg.getByText("Projeto Exemplo").first().click();
await pg.locator("#p-lista li button:not(.marcar)").first().click();
confere("tarefa dentro do projeto abre por cima, sem fechar o projeto", await pg.locator("#dlg-tarefa").evaluate((d) => d.open) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click(); await pg.click("#p-adicionar");
confere("Adicionar tarefa no projeto já vem com o projeto", (await pg.inputValue("#t-projeto")) === "p1");
await pg.locator("#dlg-tarefa [data-fechar]").last().click();
confere("cancelar a tarefa volta para o projeto aberto", !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.fill("#p-descricao", "Texto ainda não salvo"); await pg.click("#p-adicionar");
n3 = (await grav()).length; await pg.fill("#t-titulo", "Tarefa pelo projeto"); await pg.fill("#t-prazo", "2030-06-10"); await pg.locator("#form-tarefa [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar a tarefa grava no projeto e volta para ele", (await grav()).slice(n3).some((x) => x[0] === "tarefas" && x[1] === "insert" && x[2].projeto_id === "p1") && !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
confere("a descrição digitada no projeto não se perde", (await pg.inputValue("#p-descricao")) === "Texto ainda não salvo");
n3 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("depois da tarefa, salvar o projeto grava a descrição", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].descricao === "Texto ainda não salvo"));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click();
n3 = (await grav()).length; await pg.fill("#p-titulo", "Projeto editado"); await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar projeto grava o título novo", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].titulo === "Projeto editado"));
await pg.click("#novo-projeto");
confere("Novo projeto abre janela vazia", (await txt("#p-janela")) === "Novo projeto");
n3 = (await grav()).length; await pg.fill("#p-titulo", "Projeto novo"); await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("criar projeto grava inserção", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "insert" && x[2].titulo === "Projeto novo"));
await fechaJanelas(); await pg.getByText("Projeto Exemplo").first().click(); await pg.click("#p-excluir");
confere("excluir projeto pede confirmação", await pg.locator("#dlg-confirma").evaluate((d) => d.open));
n3 = (await grav()).length; await pg.mouse.click(20, 20); await pg.waitForTimeout(200);
confere("clicar fora da confirmação vale como não: fecha e não exclui", !(await pg.locator("#dlg-confirma").evaluate((d) => d.open)) && (await grav()).length === n3 && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.click("#p-excluir");
n3 = (await grav()).length; await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("confirmar exclusão manda para a lixeira", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[2] && x[2].arquivado_em));
await fechaJanelas();
// Ideias (etapa I2): tela, registro, janela, vincular, status e exclusão
await pg.click("[data-visao='ideias']");
confere("Ideias: abre a tela, com o resumo e o item marcado no menu", await pg.locator("#visao-ideias").isVisible() && (await txt("#resumo-ideias")) === "3 ideias · 1 avulsa" && (await pg.locator(".menu [data-visao='ideias']").getAttribute("aria-current")) === "page");
confere("Ideias: lista da mais recente para a mais antiga", (await pg.locator("#lista-ideias .linha-tarefa .nome").allInnerTexts()).join("|") === "Ideia do Bruno no projeto|Ideia avulsa de exemplo");
confere("Ideias: linha no modelo do cartão (texto e projeto, etiquetas de status e data, autor)", (await pg.locator("#lista-ideias .linha-tarefa").first().evaluate((c) => [...c.children].map((x) => x.className.split(" ")[0]).join("|"))) === "abrir|chips|avatar" && /^Em análise \d+ \w{3}$/.test((await pg.locator("#lista-ideias .linha-tarefa .chips").first().innerText()).replace(/\s+/g, " ").trim()) && (await pg.locator("#lista-ideias .linha-tarefa .origem").allInnerTexts()).join("|") === "Projeto Exemplo|Ideia avulsa" && (await pg.locator("#lista-ideias .linha-tarefa .avatar").first().innerText()) === "BS");
await pg.selectOption("#filtro-ideia-projeto", "avulsas");
confere("Ideias: filtro Somente avulsas", (await pg.locator("#lista-ideias .linha-tarefa .nome").allInnerTexts()).join("|") === "Ideia avulsa de exemplo");
await pg.selectOption("#filtro-ideia-status", "aprovada");
confere("Ideias: filtro sem resultado avisa", (await txt("#lista-ideias")) === "Nenhuma ideia com esses filtros.");
await pg.selectOption("#filtro-ideia-projeto", "todos"); await pg.selectOption("#filtro-ideia-status", "todos");
await pg.click("#ideia-nova"); await pg.waitForTimeout(100);
confere("I5: o botão Nova ideia abre a janela de criação, com título, descrição e projeto, sem status, Excluir nem participação", await abertaPC("#dlg-ideia") && (await txt("#i-janela")) === "Nova ideia" && await pg.locator("#i-titulo").isVisible() && await pg.locator("#i-descricao").isVisible() && await pg.locator("#i-campo-projeto").isVisible() && !(await pg.locator("#i-campo-status").isVisible()) && !(await pg.locator("#i-excluir").isVisible()) && !(await pg.locator("#i-participacao").isVisible()) && !(await pg.locator("#i-sem-participacao").isVisible()));
confere("I5: a ideia nova começa avulsa, e a nota diz que só a pessoa vê", (await pg.inputValue("#i-projeto")) === "" && (await txt("#i-destino-nota")).startsWith("Ideia avulsa: só você vê."));
n3 = (await grav()).length; await pg.locator("#i-salvar").click(); await pg.waitForTimeout(100);
confere("I5: sem título, Salvar não grava nada", (await grav()).length === n3 && await abertaPC("#dlg-ideia"));
await pg.fill("#i-titulo", "Ideia nova pelo Enter"); await pg.press("#i-titulo", "Enter"); await pg.waitForTimeout(200);
confere("I5: Enter no título registra a ideia avulsa, sem descrição, fecha a janela e avisa", (await grav()).slice(n3).some((x) => x[0] === "ideias" && x[1] === "insert" && x[2].titulo === "Ideia nova pelo Enter" && x[2].descricao === null && x[2].projeto_id === null && !("texto" in x[2])) && !(await abertaPC("#dlg-ideia")) && (await txt("#aviso")) === "Ideia registrada.");
await pg.click("#ideia-nova"); await pg.fill("#i-titulo", "Ideia com descrição"); await pg.fill("#i-descricao", "Detalhes da ideia"); await pg.selectOption("#i-projeto", "p1");
confere("I5: ao escolher um projeto, a nota avisa quem vai ver", (await txt("#i-destino-nota")) === "Todos que têm acesso ao projeto e o administrador vão ver esta ideia.");
await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("I5: com algo digitado, clicar fora não fecha a janela da ideia", await abertaPC("#dlg-ideia"));
n3 = (await grav()).length; await pg.locator("#i-salvar").click(); await pg.waitForTimeout(200);
confere("I5: Salvar grava título, descrição e o projeto escolhido", (await grav()).slice(n3).some((x) => x[0] === "ideias" && x[1] === "insert" && x[2].titulo === "Ideia com descrição" && x[2].descricao === "Detalhes da ideia" && x[2].projeto_id === "p1") && (await txt("#aviso")) === "Ideia registrada no projeto.");
await pg.click("#ideia-nova"); await pg.fill("#i-titulo", "Não vai ser gravada"); n3 = (await grav()).length; await pg.locator("#i-cancelar").click(); await pg.waitForTimeout(100);
confere("I5: Cancelar fecha a janela sem gravar", !(await abertaPC("#dlg-ideia")) && (await grav()).length === n3);
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia avulsa de exemplo" }).click();
confere("Ideias: a própria ideia abre com título, descrição, status, projeto e Excluir", await abertaPC("#dlg-ideia") && (await pg.inputValue("#i-titulo")) === "Ideia avulsa de exemplo" && await pg.locator("#i-campo-projeto").isVisible() && await pg.locator("#i-excluir").isVisible() && !(await pg.locator("#i-leitura").isVisible()) && (await txt("#i-origem")) === "Ideia avulsa: só você vê" && /Registrada por Ana Teste em \d\d\/\d\d\/\d{4} às \d\d:\d\d\./.test(await txt("#i-historico")));
await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("Ideias: sem alteração, clicar fora fecha a janela da ideia", !(await abertaPC("#dlg-ideia")));
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia avulsa de exemplo" }).click();
await pg.selectOption("#i-projeto", "p1"); n3 = (await grav()).length; await pg.click("#i-salvar"); await pg.waitForTimeout(100);
confere("Ideias: vincular a um projeto pede confirmação, avisando quem vai ver", await abertaPC("#dlg-confirma") && (await txt("#confirma-texto")).includes("\"Projeto Exemplo\"") && (await txt("#confirma-texto")).includes("visível para todos que têm acesso") && (await txt("#confirma-sim")) === "Vincular" && (await pg.locator("#confirma-sim").getAttribute("class")) === "btn primario");
await pg.click("#confirma-nao"); await pg.waitForTimeout(100);
confere("Ideias: sem confirmar, nada é gravado e a janela continua aberta", (await grav()).length === n3 && await abertaPC("#dlg-ideia"));
await pg.click("#i-salvar"); await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("Ideias: confirmando, grava só o projeto novo", (await grav()).slice(n3).some((x) => x[0] === "ideias" && x[1] === "update" && JSON.stringify(x[2]) === '{"projeto_id":"p1"}') && !(await abertaPC("#dlg-ideia")) && (await txt("#aviso")) === "Ideia vinculada ao projeto.");
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia do Bruno no projeto" }).click();
confere("Ideias: a ideia de outra pessoa abre em leitura, sem Excluir nem campo de projeto", (await txt("#i-titulo-leitura")) === "Ideia do Bruno no projeto" && (await txt("#i-leitura")) === "Detalhes da ideia do Bruno." && !(await pg.locator("#i-campo-titulo").isVisible()) && !(await pg.locator("#i-campo-descricao").isVisible()) && !(await pg.locator("#i-campo-projeto").isVisible()) && !(await pg.locator("#i-excluir").isVisible()) && (await txt("#i-autor")).includes("Bruno Silva") && (await txt("#i-origem")) === "Projeto Exemplo");
n3 = (await grav()).length; await pg.selectOption("#i-status", "aprovada"); await pg.click("#i-salvar"); await pg.waitForTimeout(200);
confere("Ideias: o responsável do projeto muda só o status", (await grav()).slice(n3).some((x) => x[0] === "ideias" && x[1] === "update" && JSON.stringify(x[2]) === '{"status":"aprovada"}') && !(await abertaPC("#dlg-confirma")));
confere("Ideias: quem não é autor nem responsável só lê (status travado, sem Salvar)", await pg.evaluate(() => Promise.all([import("./js/estado.js"), import("./js/ideias.js")]).then(([e, m]) => {
  const p = e.estado.projetos[0], antes = p.responsavel_id; p.responsavel_id = "u3"; m.abrirIdeia("i2");
  const r = document.getElementById("i-status").disabled && document.getElementById("i-salvar").hidden && document.getElementById("i-cancelar").textContent === "Fechar";
  document.getElementById("dlg-ideia").close(); p.responsavel_id = antes; return r; })));
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia avulsa de exemplo" }).click();
n3 = (await grav()).length; await pg.click("#i-excluir");
confere("Ideias: Excluir pede confirmação, com o botão vermelho", await abertaPC("#dlg-confirma") && (await pg.locator("#confirma-sim").getAttribute("class")) === "btn perigo-cheio" && (await txt("#confirma-sim")) === "Excluir");
await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("Ideias: confirmar a exclusão manda a ideia para a lixeira", (await grav()).slice(n3).some((x) => x[0] === "ideias" && x[1] === "update" && x[2].arquivado_em) && !(await abertaPC("#dlg-ideia")));
await pg.click("[data-visao='lixeira']");
confere("Ideias: a ideia excluída aparece na lixeira de quem a escreveu, e a de outra pessoa não", (await txt("#tabela-minha-lixeira")).includes("Ideia avulsa excluída") && (await txt("#tabela-minha-lixeira")).includes("Ideia avulsa\t") && !(await txt("#tabela-minha-lixeira")).includes("Ideia de projeto excluída"));
n3 = (await grav()).length; await pg.locator("#tabela-minha-lixeira tr", { hasText: "Ideia avulsa excluída" }).getByRole("button", { name: "Restaurar" }).click(); await pg.waitForTimeout(200);
confere("Ideias: Restaurar chama restaurar_item para a ideia", (await grav()).slice(n3).some((x) => x[0] === "rpc" && x[1] === "restaurar_item" && x[2].tabela === "ideias" && x[2].item === "i8") && (await txt("#aviso")) === "Ideia restaurada.");
await pg.click("[data-visao='config']");
confere("Ideias: a lixeira geral mostra a ideia de projeto excluída, e não a avulsa", (await txt("#tabela-lixeira")).includes("Ideia de projeto excluída") && !(await txt("#tabela-lixeira")).includes("Ideia avulsa excluída"));
// Ideias dentro do projeto (etapa I3)
await pg.click("[data-visao='projetos']"); await pg.getByText("Projeto Exemplo").first().click();
confere("I3: o projeto mostra o bloco Ideias deste projeto, com a contagem", await pg.locator("#p-ideias").isVisible() && (await txt("#p-ideias-contagem")) === "2");
confere("I3: as ideias do projeto no modelo do cartão, sem a linha do projeto", (await pg.locator("#p-ideias-lista .linha-tarefa .nome").allInnerTexts()).join("|") === "Ideia do Bruno no projeto" && (await pg.locator("#p-ideias-lista .origem").count()) === 0 && (await pg.locator("#p-ideias-lista .linha-tarefa .avatar").count()) === 1);
confere("I6: o projeto mostra as abas Abertas, Executadas e Descartadas, com a contagem de cada uma", (await pg.locator("#p-abas-ideias button").allInnerTexts()).join("|") === "Abertas (1)|Executadas (0)|Descartadas (1)" && (await pg.locator("#p-abas-ideias [aria-selected='true']").innerText()) === "Abertas (1)");
await pg.locator("#p-abas-ideias button", { hasText: "Descartadas" }).click();
confere("I6: a aba Descartadas do projeto mostra a ideia descartada", (await pg.locator("#p-ideias-lista .linha-tarefa .nome").allInnerTexts()).join("|") === "Ideia descartada no projeto");
await pg.locator("#p-abas-ideias button", { hasText: "Executadas" }).click();
confere("I6: a aba Executadas do projeto, sem ideias, avisa", (await txt("#p-ideias-lista")) === "Nenhuma ideia executada.");
await pg.locator("#p-abas-ideias button", { hasText: "Abertas" }).click();
await pg.click("#p-ideia-nova"); await pg.waitForTimeout(150);
confere("I5: Nova ideia neste projeto abre a janela por cima do projeto, com o projeto escolhido e travado", await abertaPC("#dlg-ideia") && await abertaPC("#dlg-projeto") && (await pg.inputValue("#i-projeto")) === "p1" && await pg.locator("#i-projeto").isDisabled() && (await txt("#i-destino-nota")).startsWith("Todos que têm acesso ao projeto"));
await pg.fill("#i-titulo", "Ideia de dentro do projeto"); await pg.fill("#i-descricao", "Detalhe"); await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("I5: com algo digitado, clicar fora não fecha a janela da ideia nem o projeto", await abertaPC("#dlg-ideia") && await abertaPC("#dlg-projeto"));
n3 = (await grav()).length; await pg.locator("#i-salvar").click(); await pg.waitForTimeout(200);
confere("I5: Salvar grava a ideia já vinculada ao projeto, volta ao projeto e avisa", (await grav()).slice(n3).some((x) => x[0] === "ideias" && x[1] === "insert" && x[2].titulo === "Ideia de dentro do projeto" && x[2].descricao === "Detalhe" && x[2].projeto_id === "p1") && (await txt("#aviso")) === "Ideia registrada no projeto." && !(await abertaPC("#dlg-ideia")) && await abertaPC("#dlg-projeto") && await pg.evaluate(() => import("./js/estado.js").then((m) => m.estado.editando?.tipo === "projeto" && m.estado.editando?.id === "p1")));
await pg.locator("#p-ideias-lista .abrir", { hasText: "Ideia do Bruno no projeto" }).click();
confere("I3: clicar na ideia abre a janela dela por cima do projeto", await abertaPC("#dlg-ideia") && await abertaPC("#dlg-projeto") && (await txt("#i-titulo-leitura")) === "Ideia do Bruno no projeto");
await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("I3: clicar fora fecha só a ideia, e o projeto volta a ser o item em edição", !(await abertaPC("#dlg-ideia")) && await abertaPC("#dlg-projeto") && await pg.evaluate(() => import("./js/estado.js").then((m) => m.estado.editando?.tipo === "projeto" && m.estado.editando?.id === "p1")));
await pg.locator("#p-abas-ideias button", { hasText: "Descartadas" }).click(); await pg.locator("#p-ideias-lista .abrir", { hasText: "Ideia descartada no projeto" }).click(); await pg.locator("#dlg-ideia [data-fechar]").first().click();
n3 = (await grav()).length; await pg.fill("#p-titulo", "Projeto Exemplo renomeado"); await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("I3: depois de abrir e fechar uma ideia, Salvar grava o projeto certo", (await grav()).slice(n3).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].titulo === "Projeto Exemplo renomeado"));
await fechaJanelas(); await pg.click("#novo-projeto");
confere("I3: no projeto novo, ainda não salvo, o bloco de ideias não aparece", !(await pg.locator("#p-ideias").isVisible()) && !(await pg.locator("#p-tarefas").isVisible()));
await fechaJanelas();
// Apoios e comentários (etapa I4)
await pg.click("[data-visao='ideias']");
await pg.locator("#abas-ideias button", { hasText: "Descartadas" }).click();
confere("I4: na lista, a ideia com participação mostra as etiquetas de apoios e de comentários", (await pg.locator("#lista-ideias .linha-tarefa", { hasText: "Ideia descartada no projeto" }).locator(".chips .chip[title]").evaluateAll((cs) => cs.map((c) => c.title).filter((t) => /apoio|coment/.test(t)).join("|"))) === "2 apoios|2 comentários");
await pg.locator("#abas-ideias button", { hasText: "Abertas" }).click();
confere("I4: a ideia sem participação mostra só as etiquetas de status e data", (await pg.locator("#lista-ideias .linha-tarefa", { hasText: "Ideia do Bruno no projeto" }).locator(".chips .chip").count()) === 2);
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia do Bruno no projeto" }).click();
confere("I4: ideia de projeto sem participação: Apoiar, ninguém apoiou e nenhum comentário", await pg.locator("#i-participacao").isVisible() && (await txt("#i-apoiar")) === "Apoiar" && (await txt("#i-apoios")) === "Ninguém apoiou ainda" && (await txt("#i-comentarios-contagem")) === "0" && (await txt("#i-comentarios")) === "Nenhum comentário ainda." && !(await pg.locator("#i-sem-participacao").isVisible()));
n3 = (await grav()).length; await pg.click("#i-apoiar"); await pg.waitForTimeout(200);
confere("I4: Apoiar grava o apoio na hora", (await grav()).slice(n3).some((x) => x[0] === "ideia_apoios" && x[1] === "insert" && x[2].ideia_id === "i2") && await abertaPC("#dlg-ideia"));
await pg.fill("#i-comentario-texto", "Um comentário"); await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("I4: com texto no comentário, clicar fora não fecha a janela", await abertaPC("#dlg-ideia"));
n3 = (await grav()).length; await pg.press("#i-comentario-texto", "Enter"); await pg.waitForTimeout(200);
confere("I4: Enter grava o comentário na hora e limpa o campo", (await grav()).slice(n3).some((x) => x[0] === "ideia_comentarios" && x[1] === "insert" && x[2].ideia_id === "i2" && x[2].texto === "Um comentário") && (await pg.inputValue("#i-comentario-texto")) === "" && await abertaPC("#dlg-ideia"));
n3 = (await grav()).length; await pg.click("#i-comentar"); await pg.waitForTimeout(100);
confere("I4: Comentar com o campo vazio não grava nada", (await grav()).length === n3);
await pg.mouse.click(20, 20); await pg.waitForTimeout(100);
confere("I4: comentar não conta como alteração: clicar fora fecha a janela depois", !(await abertaPC("#dlg-ideia")));
await pg.locator("#abas-ideias button", { hasText: "Descartadas" }).click();
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia descartada no projeto" }).click();
confere("I4: ideia própria com participação: campo Projeto travado, com a explicação", await pg.locator("#i-projeto").isDisabled() && await pg.locator("#i-projeto-nota").isVisible());
confere("I4: apoios com a contagem, os nomes e o botão marcado para quem já apoiou", (await txt("#i-apoiar")) === "Apoiada por você" && (await pg.locator("#i-apoiar").getAttribute("aria-pressed")) === "true" && (await txt("#i-apoios")) === "2 apoios" && /Bruno Silva/.test(await pg.locator("#i-apoios").getAttribute("title")) && /Ana Teste/.test(await pg.locator("#i-apoios").getAttribute("title")));
confere("I4: comentários do mais antigo para o mais novo, com nome e data; Excluir só no próprio", (await pg.locator("#i-comentarios .comentario .descricao").allInnerTexts()).join("|") === "Comentário do Bruno|Comentário da Ana" && /Bruno Silva\s+\d\d\/\d\d\/\d{4} às \d\d:\d\d/.test(await pg.locator("#i-comentarios .comentario").first().innerText()) && (await pg.locator("#i-comentarios .comentario").first().locator(".excluir-comentario").count()) === 0 && (await pg.locator("#i-comentarios .comentario").nth(1).locator(".excluir-comentario").count()) === 1 && (await txt("#i-comentarios-contagem")) === "2");
await pg.click("#i-apoios");
confere("I4: tocar na contagem mostra quem apoiou", (await txt("#aviso")).startsWith("Apoiada por: ") && (await txt("#aviso")).includes("Bruno Silva"));
n3 = (await grav()).length; await pg.click("#i-apoiar"); await pg.waitForTimeout(200);
confere("I4: tirar o apoio apaga só o apoio da pessoa", (await grav()).slice(n3).some((x) => x[0] === "ideia_apoios" && x[1] === "delete" && x[2].ideia_id === "i3" && x[2].usuario_id === "u1"));
n3 = (await grav()).length; await pg.locator("#i-comentarios .excluir-comentario").click();
confere("I4: excluir o próprio comentário pede confirmação", await abertaPC("#dlg-confirma"));
await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("I4: confirmando, apaga o comentário certo", (await grav()).slice(n3).some((x) => x[0] === "ideia_comentarios" && x[1] === "delete" && x[2].id === "c2") && await abertaPC("#dlg-ideia"));
await fechaJanelas(); await pg.locator("#abas-ideias button", { hasText: "Abertas" }).click();
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia avulsa de exemplo" }).click();
confere("I4: ideia avulsa não tem apoios nem comentários, só o aviso", !(await pg.locator("#i-participacao").isVisible()) && await pg.locator("#i-sem-participacao").isVisible() && !(await pg.locator("#i-projeto").isDisabled()));
await fechaJanelas();
// Etapa 4: lixeiras, Configurações e convites
await pg.reload(); await pg.waitForSelector("#app:not([hidden])");
await pg.click("[data-visao='lixeira']");
confere("minha lixeira lista os itens excluídos", (await txt("#tabela-minha-lixeira")).includes("Tarefa excluída") && /Tarefa avulsa/.test(await txt("#tabela-minha-lixeira")));
n3 = (await grav()).length; await pg.locator("#tabela-minha-lixeira button", { hasText: "Restaurar" }).first().click(); await pg.waitForTimeout(200);
confere("Restaurar na minha lixeira chama restaurar_item", (await grav()).slice(n3).some((x) => x[0] === "rpc" && x[1] === "restaurar_item" && x[2].tabela === "tarefas"));
await pg.click("[data-visao='config']");
confere("Configurações lista usuários e colunas", (await txt("#tabela-usuarios")).includes("Ana Teste (você)") && (await txt("#tabela-colunas-tarefas")).includes("A fazer"));
confere("lixeira geral mostra só tarefa de projeto", (await txt("#tabela-lixeira")).includes("Tarefa de projeto excluída") && !(await txt("#tabela-lixeira")).includes("Tarefa excluída\n"));
n3 = (await grav()).length; await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).getByRole("button", { name: "Bloquear" }).click(); await pg.waitForTimeout(200);
confere("Bloquear usuário grava ativo = false", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].ativo === false));
n3 = (await grav()).length; await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).locator("select").selectOption("admin"); await pg.waitForTimeout(200);
confere("trocar tipo de usuário grava o papel", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].papel === "admin"));
n3 = (await grav()).length; await pg.locator("#tabela-colunas-tarefas tr", { hasText: "A fazer" }).getByRole("button", { name: "Descer" }).click(); await pg.waitForTimeout(200);
confere("Descer coluna grava a nova ordem", (await grav()).slice(n3).some((x) => x[0] === "colunas" && x[2] && "ordem" in x[2]));
await pg.locator("#tabela-colunas-projetos tr", { hasText: "Concluído" }).getByRole("button", { name: "Editar" }).click();
confere("Editar coluna abre a janela preenchida", (await pg.inputValue("#c-nome")) === "Concluído" && await pg.isChecked("#c-concluida"));
n3 = (await grav()).length; await pg.fill("#c-nome", "Feito"); await pg.locator("#form-coluna [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar coluna grava o nome", (await grav()).slice(n3).some((x) => x[0] === "colunas" && x[1] === "update" && x[2].nome === "Feito"));
await pg.locator("[data-nova-coluna]").first().click();
confere("Nova coluna abre a janela vazia", (await txt("#c-janela")) === "Nova coluna" && (await pg.inputValue("#c-nome")) === "");
await fechaJanelas();
await pg.locator("#tabela-colunas-tarefas tr", { hasText: "A fazer" }).getByRole("button", { name: "Excluir" }).click();
confere("excluir coluna com cartões avisa e não apaga", /ainda tem \d+ cart/.test(await txt("#aviso")));
n3 = (await grav()).length; await pg.locator("#tabela-lixeira").getByRole("button", { name: "Excluir de vez" }).first().click();
confere("Excluir de vez pede confirmação", await pg.locator("#dlg-confirma").evaluate((d) => d.open));
await pg.click("#confirma-sim"); await pg.waitForTimeout(200);
confere("confirmar apaga do banco", (await grav()).slice(n3).some((x) => x[1] === "delete"));
n3 = (await grav()).length; await pg.locator("#tabela-lixeira").getByRole("button", { name: "Restaurar" }).first().click(); await pg.waitForTimeout(200);
confere("Restaurar na lixeira geral chama restaurar_item", (await grav()).slice(n3).some((x) => x[0] === "rpc"));
await pg.click("#convidar");
confere("Convidar abre a janela", await pg.locator("#dlg-convite").evaluate((d) => d.open));
await pg.fill("#v-nome", "Carla"); await pg.fill("#v-email", "carla@exemplo.com"); n3 = (await grav()).length; await pg.click("#v-gerar"); await pg.waitForTimeout(300);
confere("gerar convite chama a função e mostra o link", (await grav()).slice(n3).some((x) => x[0] === "funcao" && x[2].acao === "convidar") && /\?convite=tok123&tipo=invite$/.test(await pg.inputValue("#v-link")));
await fechaJanelas(); n3 = (await grav()).length;
await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).getByRole("button", { name: "Gerar novo link" }).click(); await pg.waitForTimeout(200);
confere("Gerar novo link pede confirmação e avisa que a senha atual deixa de valer", await pg.locator("#dlg-confirma").evaluate((d) => d.open) && /Bruno Silva.*senha atual deixa de valer/.test(await txt("#confirma-texto")) && (await txt("#confirma-sim")) === "Gerar novo link");
await pg.click("#confirma-nao"); await pg.waitForTimeout(200);
confere("Gerar novo link: sem confirmar, a função não é chamada", !(await grav()).slice(n3).some((x) => x[0] === "funcao" && x[2].acao === "novo_link") && !(await pg.locator("#dlg-convite").evaluate((d) => d.open)));
confere("Configurações mostra \"Aguardando senha\" para quem ainda não criou a senha", (await pg.locator("#tabela-usuarios tr", { hasText: "Abel Costa" }).locator(".selo").innerText()) === "Aguardando senha" && (await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).locator(".selo").innerText()) === "Liberado");
await pg.locator("#tabela-usuarios tr", { hasText: "Abel Costa" }).getByRole("button", { name: "Gerar novo link" }).click(); await pg.waitForTimeout(200);
confere("Gerar novo link para quem aguarda a senha: a pergunta fala do link anterior", /Abel Costa.*link enviado antes deixa de valer/.test(await txt("#confirma-texto")));
await pg.click("#confirma-nao"); await pg.waitForTimeout(200);
await pg.locator("#tabela-usuarios tr", { hasText: "Bruno Silva" }).getByRole("button", { name: "Gerar novo link" }).click(); await pg.waitForTimeout(200); await pg.click("#confirma-sim"); await pg.waitForTimeout(300);
confere("Gerar novo link mostra link de nova senha", (await grav()).slice(n3).some((x) => x[0] === "funcao" && x[2].acao === "novo_link") && /tipo=recovery$/.test(await pg.inputValue("#v-link")));
await fechaJanelas();
await pg.click("#btn-conta");
confere("Minha conta abre com o nome", (await pg.inputValue("#m-nome")) === "Ana Teste");
// Tema: claro, escuro ou o do aparelho, guardado no aparelho
const temaAtual = () => pg.evaluate(() => [document.documentElement.dataset.tema, getComputedStyle(document.body).backgroundColor, localStorage.getItem("gp-tema"), document.querySelector("[data-tema-opcao][aria-pressed='true']")?.dataset.temaOpcao].join("|"));
confere("tema: sem escolha, segue o aparelho (claro) e a opção vem marcada", (await temaAtual()) === "claro|rgb(245, 244, 240)||seguir");
await pg.click("[data-tema-opcao='escuro']");
confere("tema: Escuro muda na hora, sem Salvar, e fica guardado no aparelho", (await temaAtual()) === "escuro|rgb(17, 19, 23)|escuro|escuro" && await pg.locator("#dlg-conta").evaluate((d) => d.open && !d.dataset.alterado));
await pg.emulateMedia({ colorScheme: "dark" }); await pg.click("[data-tema-opcao='claro']");
confere("tema: Claro vale mesmo com o aparelho em escuro", (await temaAtual()) === "claro|rgb(245, 244, 240)|claro|claro");
await pg.click("[data-tema-opcao='seguir']");
confere("tema: Seguir o aparelho apaga a escolha e acompanha o aparelho (escuro)", (await temaAtual()) === "escuro|rgb(17, 19, 23)||seguir");
await pg.emulateMedia({ colorScheme: "light" }); await pg.waitForTimeout(100);
confere("tema: seguindo o aparelho, a troca de tema do aparelho vale na hora", (await temaAtual()).startsWith("claro|rgb(245, 244, 240)"));
await pg.click("[data-tema-opcao='escuro']"); await pg.reload(); await pg.waitForSelector("#app:not([hidden])");
confere("tema: a escolha continua depois de recarregar, já antes de o site desenhar", (await pg.evaluate(() => document.documentElement.dataset.tema)) === "escuro" && await pg.evaluate(() => !!document.querySelector("head script[src='js/tema.js']") && document.querySelector("head script[src='js/tema.js']").compareDocumentPosition(document.querySelector("link[href='css/estilo.css']")) === Node.DOCUMENT_POSITION_FOLLOWING));
await pg.evaluate(() => { localStorage.removeItem("gp-tema"); }); await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); await pg.click("#btn-conta");
n3 = (await grav()).length; await pg.fill("#m-nome", "Ana T."); await pg.locator("#form-conta [type='submit']").click(); await pg.waitForTimeout(200);
confere("salvar Minha conta grava o nome", (await grav()).slice(n3).some((x) => x[0] === "perfis" && x[2] && x[2].nome === "Ana T."));
await pg.goto("http://localhost:8123/?convite=abc"); await pg.waitForSelector("#tela-senha:not([hidden])");
confere("link de convite abre a tela de criar senha", (await txt("#senha-titulo")) === "Crie a sua senha");
await pg.reload(); await pg.waitForTimeout(400);
confere("link de convite: recarregar sem criar a senha volta para a tela de senha, sem entrar na conta", await pg.locator("#tela-senha").isVisible() && !(await pg.locator("#app").isVisible()) && (await txt("#senha-titulo")) === "Crie a sua senha");
await pg.fill("#senha-nova", "Senha-de-teste-1"); await pg.fill("#senha-repete", "Senha-de-teste-1"); await pg.locator("#form-senha [type='submit']").click(); await pg.waitForSelector("#app:not([hidden])");
await pg.reload(); await pg.waitForSelector("#app:not([hidden])");
confere("link de convite: depois de criar a senha, entra e continua dentro ao recarregar", await pg.evaluate(() => localStorage.getItem("takt.senha-pendente") === null));
// Trava do banco: perfil com a senha pendente não entra, mesmo sem a marca no aparelho
await pg.goto("http://localhost:8123/?pendente=1"); await pg.waitForTimeout(400);
confere("senha pendente no banco: o site pede a senha e não abre os dados, mesmo sem a marca no aparelho", await pg.locator("#tela-senha").isVisible() && !(await pg.locator("#app").isVisible()) && (await txt("#senha-titulo")) === "Defina uma nova senha");
await pg.fill("#senha-nova", "Senha-de-teste-2"); await pg.fill("#senha-repete", "Senha-de-teste-2"); await pg.locator("#form-senha [type='submit']").click(); await pg.waitForSelector("#app:not([hidden])");
confere("senha pendente no banco: gravada a senha, o site entra", await pg.locator("#app").isVisible());
await pg.goto("http://localhost:8123/#config"); await pg.waitForSelector("#app:not([hidden])");
confere("Configurações: \"Gerar novo link\" fica desligado na própria linha e ligado nas demais", await pg.locator("#tabela-usuarios tr").evaluateAll((l) => l.slice(1).map((r) => [...r.querySelectorAll("button")].find((x) => x.textContent === "Gerar novo link").disabled).join()) === "true,false,false");
// Celular: moldura fixa, barra de baixo e painel "Mais"
await pg.setViewportSize({ width: 390, height: 844 }); await pg.goto("http://localhost:8123/"); await pg.waitForSelector("#app:not([hidden])");
confere("celular: a página não rola nem para os lados nem para baixo", await pg.evaluate(() => document.documentElement.scrollWidth === innerWidth && document.documentElement.scrollHeight === innerHeight));
const caixa = await pg.locator(".menu").boundingBox();
confere("celular: barra de baixo encostada no rodapé, com quatro itens (Projetos, Tarefas, Ideias, Mais)", Math.round(caixa.y + caixa.height) === 844 && (await pg.locator(".menu button:visible").allInnerTexts()).map((t) => t.trim()).join("|") === "Projetos|Tarefas|Ideias|Mais");
// Celular: quadro com uma coluna por vez
const colunaVisivel = (q) => pg.locator(`#quadro-${q} .coluna:visible`).evaluateAll((l) => l.map((c) => c.dataset.coluna).join());
confere("celular: o quadro mostra uma coluna por vez, a primeira", (await colunaVisivel("projetos")) === "cp1");
confere("celular: etiquetas com o nome e a contagem de cada coluna", (await pg.locator("#quadro-projetos .etiquetas button").allInnerTexts()).map((x) => x.replace(/\s+/g, " ").trim()).join("|") === "A fazer 1|Concluído 0");
confere("celular: o quadro não traz mais a frase de como mudar de coluna", (await pg.locator(".dica-coluna").count()) === 0);
confere("celular: o quadro não rola para os lados e o cartão ocupa a largura", await pg.locator("#quadro-projetos").evaluate((q) => getComputedStyle(q).overflowX === "visible" && q.querySelector(".cartao").getBoundingClientRect().width > 340));
confere("celular: o cartão não é arrastável", await pg.locator("#quadro-projetos .cartao").first().evaluate((c) => c.draggable === false));
await pg.locator("#quadro-projetos .etiquetas button", { hasText: "Concluído" }).click();
confere("celular: tocar na etiqueta troca a coluna", (await colunaVisivel("projetos")) === "cp2" && (await pg.locator("#quadro-projetos .etiquetas [aria-selected='true']").innerText()).includes("Concluído"));
await pg.click("[data-visao='tarefas']"); await pg.locator("[data-modo='quadro']").click();
confere("celular: cada quadro tem a sua coluna (Tarefas segue na primeira)", (await colunaVisivel("tarefas")) === "ct1" && (await pg.locator("#quadro-tarefas .dica-coluna").count()) === 0);
await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); await pg.click("[data-visao='projetos']");
confere("celular: ao voltar, o quadro mostra a última coluna em que a pessoa esteve", (await colunaVisivel("projetos")) === "cp2");
await pg.evaluate(() => localStorage.setItem("gp-coluna-projetos", "coluna-que-sumiu")); await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); await pg.click("[data-visao='projetos']");
confere("celular: se a coluna guardada não existe mais, mostra a primeira", (await colunaVisivel("projetos")) === "cp1");
// Celular: o projeto abre em leitura, em tela cheia
await pg.locator("#quadro-projetos .cartao").first().click(); await pg.waitForTimeout(350);
const telaCheia = () => pg.locator("#dlg-projeto").evaluate((d) => { const r = d.getBoundingClientRect(); return Math.round(r.left) === 0 && Math.round(r.top) === 0 && Math.round(r.width) === innerWidth && Math.round(r.height) === innerHeight && getComputedStyle(d).borderTopLeftRadius === "0px"; });
confere("celular: projeto que já existe abre em leitura, em tela cheia", await telaCheia() && await pg.locator("#p-leitura").isVisible() && !(await pg.locator("#form-projeto").isVisible()));
confere("celular: a leitura do projeto segue o modelo do cartão (nome, etiquetas, andamento) e mostra responsável e histórico", (await txt("#lp-titulo")) === "Projeto Exemplo" && (await txt("#lp-chips")).replace(/\s+/g, " ").trim() === "Prioridade alta 2 pessoas 1 jan 2020" && (await txt("#lp-andamento")).includes("0 de 1 tarefa") && (await txt("#lp-responsavel")).includes("Ana Teste") && /Criado por Ana Teste/.test(await txt("#lp-historico")));
confere("celular: as tarefas do projeto no modelo da Lista, com a coluna e sem repetir o nome do projeto", await pg.locator("#lp-lista .linha-tarefa").first().evaluate((l) => l.querySelector(".nome").textContent === "Tarefa atrasada" && !l.querySelector(".origem") && l.querySelector(".chips").innerText.replace(/\s+/g, " ").trim() === "A fazer Prioridade média 1 jan 2020" && !!l.querySelector(":scope > .avatar")) && (await txt("#lp-contagem")) === "1");
confere("celular: botão de voltar em cima e Editar e Nova tarefa parados embaixo", await pg.evaluate(() => { const v = document.querySelector("#p-leitura .voltar").getBoundingClientRect(), a = document.getElementById("lp-editar").getBoundingClientRect(), b = document.getElementById("lp-nova").getBoundingClientRect(); return v.top >= 0 && v.bottom <= 60 && v.height >= 44 && Math.abs(a.top - b.top) < 1 && a.right <= b.left && b.bottom <= innerHeight && innerHeight - b.bottom < 30 && document.getElementById("lp-nova").textContent === "Nova tarefa"; }));
confere("celular: o projeto aberto não passa da largura da tela", await pg.evaluate(() => document.getElementById("dlg-projeto").scrollWidth <= innerWidth));
let n5 = (await grav()).length; await pg.selectOption("#lp-coluna", "cp2"); await pg.waitForTimeout(250);
confere("celular: o campo Coluna da leitura do projeto grava na hora e a tela continua aberta", (await grav()).slice(n5).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].coluna_id === "cp2") && await pg.locator("#dlg-projeto").evaluate((d) => d.open) && (await pg.inputValue("#lp-coluna")) === "cp2" && (await txt("#aviso")) === "Projeto movido para Concluído.");
confere("celular: o aviso aparece por cima da tela aberta", await pg.evaluate(() => { const a = document.getElementById("aviso"), r = a.getBoundingClientRect(); return a.matches(":popover-open") && r.width > 100 && r.bottom < innerHeight && Math.abs((r.left + r.right) / 2 - innerWidth / 2) < 2; }));
await pg.locator("#lp-lista .linha-tarefa .abrir").first().click(); await pg.waitForTimeout(350);
confere("celular: tocar em uma tarefa do projeto abre o painel dela por cima, em leitura", await pg.locator("#dlg-tarefa").evaluate((d) => d.open) && await pg.locator("#t-leitura").isVisible() && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.mouse.click(195, 30); await pg.waitForTimeout(150);
confere("celular: recolher o painel da tarefa volta para o projeto", !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)) && await pg.locator("#p-leitura").isVisible());
await pg.click("#lp-nova"); await pg.waitForTimeout(350);
confere("celular: Nova tarefa do projeto abre o painel no formulário, já com o projeto", await pg.locator("#form-tarefa").isVisible() && (await pg.inputValue("#t-projeto")) === "p1");
await pg.locator("#form-tarefa [data-fechar]").first().click();
await pg.locator("#lp-lista .marcar").first().click(); await pg.waitForTimeout(250);
confere("celular: concluir uma tarefa pela leitura do projeto grava e a tela continua aberta", (await grav()).some((x) => x[0] === "tarefas" && x[2] && x[2].concluida_em) && await pg.locator("#p-leitura").isVisible());
await pg.click("#lp-editar");
confere("celular: Editar troca a leitura pelo formulário do projeto, na mesma tela", await telaCheia() && await pg.locator("#form-projeto").isVisible() && !(await pg.locator("#p-leitura").isVisible()) && (await pg.inputValue("#p-titulo")) === "Projeto Exemplo" && (await pg.inputValue("#p-coluna")) === "cp2");
// Celular: quem pode ver o projeto, em painel vindo de baixo
const marcado = (nome) => pg.locator("#p-membros label", { hasText: nome }).locator("input").isChecked();
const equipeAberta = () => pg.locator("#dlg-equipe").evaluate((d) => d.open);
await pg.click("#p-membros-resumo"); await pg.waitForTimeout(350);
confere("celular: Quem pode ver abre em painel de baixo, com busca, lista, Cancelar e Aplicar", await equipeAberta() && !(await pg.locator("#p-seletor").evaluate((d) => d.open)) && await pg.locator("#dlg-equipe").evaluate((d) => { const r = d.getBoundingClientRect(); return Math.round(r.bottom) === innerHeight && Math.round(r.width) === innerWidth && r.top > 0 && !!d.querySelector("#p-membros-busca") && !!d.querySelector("#p-membros"); }) && await pg.locator("#equipe-cancelar").isVisible() && await pg.locator("#equipe-aplicar").isVisible());
confere("celular: o painel abre sem pôr o cursor na busca (o teclado não sobe sozinho)", await pg.evaluate(() => document.activeElement !== document.getElementById("p-membros-busca")));
confere("celular: no painel, o responsável vem primeiro e a pessoa da equipe vem marcada", (await pg.locator("#p-membros label").allInnerTexts()).map((x) => x.trim()).join(" | ") === "Ana Teste (responsável) | Bruno Silva | Abel Costa" && await marcado("Bruno Silva"));
await pg.fill("#p-membros-busca", "abel");
confere("celular: a busca do painel filtra a lista", await pg.locator("#p-membros label", { hasText: "Abel Costa" }).isVisible() && !(await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).isVisible()));
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").check();
await pg.mouse.click(195, 20); await pg.waitForTimeout(100);
confere("celular: com alguém marcado, tocar fora não recolhe o painel", await equipeAberta());
await pg.click("#equipe-cancelar"); await pg.waitForTimeout(100);
confere("celular: Cancelar desfaz o que foi marcado e devolve a lista ao formulário", !(await equipeAberta()) && !(await marcado("Abel Costa")) && await marcado("Bruno Silva") && await pg.evaluate(() => !!document.querySelector("#p-seletor .seletor-painel #p-membros") && document.getElementById("p-membros-busca").value === ""));
await pg.click("#p-membros-resumo"); await pg.waitForTimeout(350); await pg.mouse.click(195, 20); await pg.waitForTimeout(100);
confere("celular: sem mudança, tocar fora recolhe o painel de quem pode ver", !(await equipeAberta()) && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.click("#p-membros-resumo"); await pg.waitForTimeout(350);
await pg.locator("#p-membros label", { hasText: "Abel Costa" }).locator("input").check(); await pg.locator("#p-membros label", { hasText: "Bruno Silva" }).locator("input").uncheck();
await pg.click("#equipe-aplicar"); await pg.waitForTimeout(100);
confere("celular: Aplicar mantém o que foi marcado", !(await equipeAberta()) && await marcado("Abel Costa") && !(await marcado("Bruno Silva")));
await pg.selectOption("#p-coluna", "cp1");
n5 = (await grav()).length; await pg.locator("#form-projeto [type='submit']").click(); await pg.waitForTimeout(200);
confere("celular: mudar de coluna pelo campo Coluna do formulário grava a nova coluna", (await grav()).slice(n5).some((x) => x[0] === "projetos" && x[1] === "update" && x[2].coluna_id === "cp1"));
confere("celular: salvar o projeto grava a equipe escolhida no painel", (await grav()).slice(n5).some((x) => x[0] === "projeto_membros" && x[1] === "insert" && x[2][0].usuario_id === "u3") && (await grav()).slice(n5).some((x) => x[0] === "projeto_membros" && x[1] === "delete" && x[2].usuario_id.join() === "u2"));
await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); // os dados de exemplo voltam ao começo
await pg.locator("#quadro-projetos .cartao").first().click(); await pg.waitForTimeout(350); await pg.click("#p-leitura .voltar");
confere("celular: o botão de voltar fecha o projeto", !(await pg.locator("#dlg-projeto").evaluate((d) => d.open)));
// Celular: botão "+", painel "Novo" e cabeçalho enxuto
confere("celular: botão + no lugar do botão do topo", await pg.locator("#botao-novo").isVisible() && !(await pg.locator("#novo-projeto").isVisible()));
confere("celular: botão + dentro da moldura, acima da barra de baixo", await pg.evaluate(() => { const b = document.getElementById("botao-novo"), r = b.getBoundingClientRect(), m = document.querySelector(".menu").getBoundingClientRect(); return getComputedStyle(b).position !== "fixed" && r.bottom <= m.top && r.right <= innerWidth && b.parentElement.id === "app"; }));
await pg.click("#botao-novo");
confere("celular: + abre o painel Novo com as duas opções", await pg.locator("#dlg-novo").evaluate((d) => d.open) && await pg.locator("#novo-item-tarefa").isVisible() && await pg.locator("#novo-item-projeto").isVisible());
await pg.click("#novo-item-projeto");
confere("celular: Novo projeto pelo painel abre a janela vazia e fecha o painel", (await txt("#p-janela")) === "Novo projeto" && await pg.locator("#dlg-projeto").evaluate((d) => d.open) && !(await pg.locator("#dlg-novo").evaluate((d) => d.open)));
await pg.locator("#dlg-projeto [data-fechar]:visible").first().click();
await pg.click(".menu [data-visao='tarefas']");
confere("celular: Tarefas abre na Lista", (await pg.locator("[data-modo='lista']").getAttribute("aria-selected")) === "true" && await pg.locator("#lista-tarefas").isVisible() && !(await pg.locator("#quadro-tarefas").isVisible()));
confere("celular: na Lista, responsável na primeira linha, à direita, e nome longo com reticências", certo(await primeiraLinha("#lista-tarefas .linha-tarefa", ".nome")));
confere("celular: na Lista, as etiquetas ficam na linha de baixo, sem o responsável", await pg.locator("#lista-tarefas .linha-tarefa").first().evaluate((l) => l.querySelector(".chips").getBoundingClientRect().top >= l.querySelector(".abrir").getBoundingClientRect().bottom && !l.querySelector(".chips .avatar")));
confere("celular: alternância na ordem Lista, Quadro, Concluídas, na largura da tela", await pg.evaluate(() => { const x = (m) => document.querySelector(`[data-modo='${m}']`).getBoundingClientRect().left; const a = document.querySelector(".abas").getBoundingClientRect(); return x("lista") < x("quadro") && x("quadro") < x("concluidas") && a.width > 340 && document.querySelector("[data-modo='lista']").innerText.trim() === "Lista"; }));
confere("celular: filtro de projeto na largura da tela, sem o botão Nova tarefa", (await pg.locator("#filtro-projeto").evaluate((s) => s.getBoundingClientRect().width)) > 340 && !(await pg.locator("#nova-tarefa").isVisible()));
await pg.click("#botao-novo"); await pg.click("#novo-item-tarefa");
confere("celular: Nova tarefa pelo painel abre a janela vazia", (await txt("#t-janela")) === "Nova tarefa" && (await pg.inputValue("#t-titulo")) === "" && !(await pg.locator("#dlg-novo").evaluate((d) => d.open)));
// Celular: a janela da tarefa é um painel vindo de baixo; a tarefa que já existe abre em leitura
const painel = () => pg.locator("#dlg-tarefa").evaluate((d) => { const r = d.getBoundingClientRect(); return Math.round(r.left) === 0 && Math.round(r.width) === innerWidth && Math.round(r.bottom) === innerHeight && r.top > 0 && getComputedStyle(d).borderTopLeftRadius === "20px"; });
await pg.waitForTimeout(350);
confere("celular: tarefa nova abre o painel de baixo já no formulário", await painel() && await pg.locator("#form-tarefa").isVisible() && !(await pg.locator("#t-leitura").isVisible()));
await pg.locator("#form-tarefa [data-fechar]").first().click(); await pg.locator("[data-modo='lista']").click();
await pg.locator("#lista-tarefas .linha-tarefa", { hasText: "Tarefa atrasada" }).locator(".abrir").click(); await pg.waitForTimeout(350);
confere("celular: tarefa que já existe abre em leitura, como painel de baixo", await painel() && await pg.locator("#t-leitura").isVisible() && !(await pg.locator("#form-tarefa").isVisible()));
confere("celular: a leitura segue o modelo do cartão (nome, projeto, etiquetas) e mostra responsável e histórico", (await txt("#l-titulo")) === "Tarefa atrasada" && (await txt("#l-origem")) === "Projeto Exemplo" && (await txt("#l-chips")).replace(/\s+/g, " ").trim() === "Prioridade média 1 jan 2020" && (await txt("#l-responsavel")).includes("Ana Teste") && /Criado por Ana Teste/.test(await txt("#l-historico")));
confere("celular: rodapé da leitura com Editar e Concluir, lado a lado", await pg.evaluate(() => { const a = document.getElementById("l-editar").getBoundingClientRect(), b = document.getElementById("l-concluir").getBoundingClientRect(); return document.getElementById("l-editar").textContent === "Editar" && document.getElementById("l-concluir").textContent === "Concluir" && Math.abs(a.top - b.top) < 1 && a.right <= b.left && a.height >= 44; }));
confere("celular: o painel da tarefa não passa da largura da tela", await pg.evaluate(() => document.getElementById("dlg-tarefa").scrollWidth <= innerWidth && document.documentElement.scrollWidth === innerWidth));
// Tocar fora do painel (na parte escurecida) recolhe; formulário já mexido não recolhe
const aberta = () => pg.locator("#dlg-tarefa").evaluate((d) => d.open);
await pg.mouse.click(195, 700); await pg.waitForTimeout(100);
confere("celular: tocar dentro do painel da tarefa não recolhe", await aberta());
await pg.mouse.click(195, 30); await pg.waitForTimeout(100);
confere("celular: tocar fora do painel da tarefa recolhe o painel", !(await aberta()));
await pg.locator("#lista-tarefas .linha-tarefa", { hasText: "Tarefa atrasada" }).locator(".abrir").click(); await pg.click("#l-editar"); await pg.waitForTimeout(350);
const topoForm = await pg.locator("#dlg-tarefa").evaluate((d) => d.getBoundingClientRect().top);
await pg.fill("#t-descricao", "Texto em andamento"); await pg.mouse.click(195, topoForm - 10); await pg.waitForTimeout(100);
confere("celular: com algo digitado no formulário, tocar fora não recolhe nem apaga", (await aberta()) && (await pg.inputValue("#t-descricao")) === "Texto em andamento");
await pg.locator("#form-tarefa [data-fechar]").first().click();
await pg.locator("#lista-tarefas .linha-tarefa", { hasText: "Tarefa atrasada" }).locator(".abrir").click(); await pg.click("#l-editar"); await pg.waitForTimeout(350);
await pg.mouse.click(195, topoForm - 10); await pg.waitForTimeout(100);
confere("celular: formulário sem alteração recolhe ao tocar fora (a marca de alterado não passa de uma vez para a outra)", !(await aberta()));
await pg.click("#botao-novo"); await pg.waitForTimeout(350); await pg.mouse.click(195, 100); await pg.waitForTimeout(100);
confere("celular: tocar fora do painel Novo recolhe", !(await pg.locator("#dlg-novo").evaluate((d) => d.open)));
await pg.click("#menu-mais"); await pg.waitForTimeout(350); await pg.mouse.click(195, 100); await pg.waitForTimeout(100);
confere("celular: tocar fora do painel Mais recolhe", !(await pg.locator("#dlg-mais").evaluate((d) => d.open)));
await pg.locator("#lista-tarefas .linha-tarefa", { hasText: "Tarefa atrasada" }).locator(".abrir").click(); await pg.waitForTimeout(350);
let n6 = (await grav()).length; await pg.selectOption("#l-coluna", "ct3"); await pg.waitForTimeout(250);
confere("celular: o campo Coluna da leitura grava na hora e o painel continua aberto", (await grav()).slice(n6).some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].coluna_id === "ct3") && await pg.locator("#dlg-tarefa").evaluate((d) => d.open) && (await pg.inputValue("#l-coluna")) === "ct3" && (await txt("#aviso")) === "Tarefa movida para Em andamento.");
await pg.click("#l-editar");
confere("celular: Editar troca a leitura pelo formulário preenchido, no mesmo painel", await pg.locator("#form-tarefa").isVisible() && !(await pg.locator("#t-leitura").isVisible()) && (await pg.inputValue("#t-titulo")) === "Tarefa atrasada" && (await pg.inputValue("#t-coluna")) === "ct3" && await pg.locator("#t-excluir").isVisible() && await painel());
await pg.locator("#form-tarefa [data-fechar]").first().click();
await pg.locator("#lista-tarefas .linha-tarefa", { hasText: "Tarefa avulsa" }).locator(".abrir").click();
n6 = (await grav()).length; await pg.selectOption("#l-coluna", "ct2"); await pg.waitForTimeout(250);
confere("celular: levar para a coluna concluída pelo campo Coluna grava e fecha o painel", (await grav()).slice(n6).some((x) => x[0] === "tarefas" && x[1] === "update" && x[2].coluna_id === "ct2") && !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)));
await pg.locator("#lista-tarefas .linha-tarefa .abrir").first().click();
n6 = (await grav()).length; await pg.click("#l-concluir"); await pg.waitForTimeout(250);
confere("celular: Concluir na leitura grava a conclusão e fecha o painel", (await grav()).slice(n6).some((x) => x[0] === "tarefas" && x[2] && x[2].concluida_em) && !(await pg.locator("#dlg-tarefa").evaluate((d) => d.open)));
await pg.evaluate(() => import("./js/estado.js").then((m) => { m.estado.tarefas.find((t) => t.id === "t1").responsavel_id = "u2"; return import("./js/tarefas.js").then((t) => t.abrirTarefa("t1")); }));
confere("celular: quem não é o responsável não vê Concluir nem escolhe a coluna concluída", !(await pg.locator("#l-concluir").isVisible()) && await pg.locator("#l-editar").isVisible() && await pg.locator("#l-coluna option[value='ct2']").evaluate((o) => o.disabled));
await pg.evaluate(() => import("./js/estado.js").then((m) => { m.estado.tarefas.find((t) => t.id === "t1").responsavel_id = "u1"; }));
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click();
await pg.click("#menu-mais"); await pg.click("#dlg-mais [data-visao='lixeira']");
confere("celular: na Lixeira não há botão +", !(await pg.locator("#botao-novo").isVisible()));
await pg.click(".menu [data-visao='projetos']");
await pg.evaluate(() => localStorage.clear());
await pg.click("[data-visao='tarefas']"); await pg.locator("[data-modo='quadro']").click();
confere("celular: trocar de tela pela barra de baixo", await pg.locator("#visao-tarefas").isVisible() && (await pg.evaluate(() => document.documentElement.scrollWidth === innerWidth)));
await pg.click("#menu-mais");
confere("celular: Mais abre o painel com Configurações para o admin", await pg.locator("#dlg-mais").evaluate((d) => d.open) && await pg.locator("#mais-config").isVisible());
await pg.click("#dlg-mais [data-visao='lixeira']");
confere("celular: Lixeira pelo painel Mais abre a tela e fecha o painel", await pg.locator("#visao-lixeira").isVisible() && !(await pg.locator("#dlg-mais").evaluate((d) => d.open)));
await pg.click("#menu-mais"); await pg.click("#mais-conta");
confere("celular: Minha conta pelo painel Mais", await pg.locator("#dlg-conta").evaluate((d) => d.open) && !(await pg.locator("#dlg-mais").evaluate((d) => d.open)));
await pg.waitForTimeout(350);
const deBaixo = (id) => pg.locator(id).evaluate((d) => { const r = d.getBoundingClientRect(); return Math.round(r.left) === 0 && Math.round(r.width) === innerWidth && Math.round(r.bottom) === innerHeight && r.top > 0 && getComputedStyle(d).borderTopLeftRadius === "20px" && getComputedStyle(d, "::before").width === "40px"; });
confere("celular: Minha conta é um painel vindo de baixo, com a alça", await deBaixo("#dlg-conta"));
confere("celular: campos com letra de 16 px, para o iPhone não ampliar a tela", await pg.evaluate(() => [...document.querySelectorAll("input:not([type=checkbox]), select, textarea")].every((c) => parseFloat(getComputedStyle(c).fontSize) >= 16)));
await pg.keyboard.press("Escape"); await pg.click(".menu [data-visao='tarefas']"); await pg.locator("[data-modo='lista']").click(); await pg.locator("#lista-tarefas .abrir").first().click(); await pg.click("#l-editar");
await pg.click("#t-excluir"); await pg.waitForTimeout(350);
confere("celular: a confirmação é um painel vindo de baixo, por cima do painel da tarefa", await deBaixo("#dlg-confirma") && await pg.locator("#dlg-tarefa").evaluate((d) => d.open));
await pg.click("#confirma-nao");
confere("celular: o campo de data tem a mesma largura dos outros campos", await pg.evaluate(() => { const l = (id) => Math.round(document.getElementById(id).getBoundingClientRect().width); return l("t-prazo") === l("t-titulo") && l("t-prazo") === l("t-responsavel"); }));
await pg.locator("#form-tarefa [data-fechar]").first().click();
await pg.click(".menu [data-visao='ideias']");
confere("celular: Ideias pela barra de baixo, com o botão + e sem rolagem para os lados", await pg.locator("#visao-ideias").isVisible() && await pg.locator("#botao-novo").isVisible() && await pg.evaluate(() => document.querySelector(".palco").scrollWidth <= document.querySelector(".palco").clientWidth));
confere("celular: na linha da ideia, o autor fica na primeira linha e as etiquetas embaixo, sem recuo", await pg.locator("#lista-ideias .linha-tarefa").first().evaluate((c) => { const n = c.querySelector(".nome").getBoundingClientRect(), a = c.querySelector(".avatar").getBoundingClientRect(), k = c.querySelector(".chips").getBoundingClientRect(); return a.top < n.bottom && a.left > n.right && k.top > n.bottom && Math.round(k.left) === Math.round(n.left); }));
await pg.click("#botao-novo"); await pg.waitForTimeout(350);
confere("celular: em Ideias o botão + abre direto a janela da nova ideia, vinda de baixo", await deBaixo("#dlg-ideia") && (await txt("#i-janela")) === "Nova ideia");
await pg.locator("#dlg-ideia [data-fechar]").first().click(); await pg.waitForTimeout(100);
await pg.locator("#lista-ideias .abrir").first().click(); await pg.waitForTimeout(350);
confere("celular: a ideia abre em painel vindo de baixo", await deBaixo("#dlg-ideia"));
await pg.locator("#dlg-ideia [data-fechar]").first().click();
await pg.evaluate(() => import("./js/projetos.js").then((m) => m.abrirProjeto("p1"))); await pg.waitForTimeout(350);
confere("celular: na leitura do projeto, as ideias vêm depois das tarefas, sem a linha do projeto", await pg.locator("#lp-ideias").isVisible() && (await pg.locator("#lp-ideias-lista .linha-tarefa").count()) === 1 && (await pg.locator("#lp-ideias-lista .origem").count()) === 0 && await pg.evaluate(() => document.getElementById("lp-tarefas").compareDocumentPosition(document.getElementById("lp-ideias")) & Node.DOCUMENT_POSITION_FOLLOWING));
await pg.click("#lp-ideia-nova"); await pg.waitForTimeout(350);
confere("celular: Nova ideia neste projeto abre de baixo, por cima do projeto, com o projeto escolhido e travado", await deBaixo("#dlg-ideia") && await pg.locator("#dlg-projeto").evaluate((d) => d.open) && (await pg.inputValue("#i-projeto")) === "p1" && await pg.locator("#i-projeto").isDisabled());
{ const antesP = (await grav()).length; await pg.fill("#i-titulo", "Ideia pelo celular"); await pg.press("#i-titulo", "Enter"); await pg.waitForTimeout(200);
confere("celular: Enter no título grava a ideia no projeto e a janela volta para o projeto", (await grav()).slice(antesP).some((x) => x[0] === "ideias" && x[1] === "insert" && x[2].titulo === "Ideia pelo celular" && x[2].projeto_id === "p1") && !(await pg.locator("#dlg-ideia").evaluate((d) => d.open)) && await pg.locator("#dlg-projeto").evaluate((d) => d.open)); }
await pg.locator("#lp-ideias-lista .abrir").first().click(); await pg.waitForTimeout(350);
confere("celular: a ideia aberta de dentro do projeto sobe de baixo, por cima do projeto", await deBaixo("#dlg-ideia") && await pg.locator("#dlg-projeto").evaluate((d) => d.open));
await pg.locator("#dlg-ideia [data-fechar]").first().click(); await pg.locator("#lp-abas-ideias button", { hasText: "Descartadas" }).click(); await pg.locator("#lp-ideias-lista .abrir", { hasText: "Ideia descartada no projeto" }).click(); await pg.waitForTimeout(350);
await pg.fill("#i-comentario-texto", "Comentário no celular"); await pg.press("#i-comentario-texto", "Enter");
{ const antesC = (await grav()).length; await pg.click("#i-comentar"); await pg.waitForTimeout(200);
confere("celular: comentários e apoiar na janela da ideia; Enter quebra a linha e o botão Comentar grava", await pg.locator("#i-participacao").isVisible() && (await pg.locator("#i-comentarios .comentario").count()) === 2 && (await grav()).slice(antesC).some((x) => x[0] === "ideia_comentarios" && x[1] === "insert" && x[2].texto === "Comentário no celular") && await pg.evaluate(() => document.getElementById("dlg-ideia").scrollWidth <= document.getElementById("dlg-ideia").clientWidth)); }
await fechaJanelas();
confere("sem #diag, a caixa de diagnóstico não existe", (await pg.locator("#diagnostico").count()) === 0);
await pg.goto("http://localhost:8123/#diag"); await pg.reload(); await pg.waitForSelector("#diagnostico");
confere("com #diag, a caixa de diagnóstico mostra as medidas", /janela \(inner\)\s+390 x 844/.test(await txt("#diagnostico")) && /barra de baixo\s+topo/.test(await txt("#diagnostico")));
// Versão do site e atualização de páginas já abertas
const versaoNoArquivo = fs.readFileSync(path.join(raiz, "js/versao.js"), "utf8").match(/VERSAO = "(\d{4}\.\d{2}\.\d{2}-\d+)"/)?.[1];
confere("versao.js traz a versão no formato ano.mês.dia-ordem", !!versaoNoArquivo);
confere("com #diag, a caixa mostra a versão do site", (await txt("#diagnostico")).includes("versão do site      " + versaoNoArquivo));
await pg.goto("http://localhost:8123/"); await pg.reload(); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(300);
confere("com a mesma versão publicada, a página não avisa nem recarrega", (await pg.locator("#aviso-versao").count()) === 0 && (await pg.evaluate(() => sessionStorage.getItem("gp-atualizou-para"))) === null);
await pg.click("#menu-mais"); await pg.click("#mais-conta");
confere("Minha conta mostra a versão do site", (await txt("#versao-do-site")) === "Versão do site: " + versaoNoArquivo);
// Daqui em diante o servidor "publica" outra versão: só a consulta de versão (com ?t=) recebe o arquivo novo
await pg.route(/\/js\/versao\.js\?t=/, (r) => r.fulfill({ contentType: "text/javascript", body: 'export const VERSAO = "2099.01.01-1";' }));
const confereVersao = () => pg.evaluate(() => import("./js/atualizacao.js").then((m) => m.conferirVersao(true)));
let cargas = 0; pg.on("load", () => cargas++);
await confereVersao(); await pg.waitForTimeout(300);
confere("versão nova com janela aberta: avisa e não recarrega", (await pg.locator("#aviso-versao").count()) === 1 && cargas === 0 && await pg.locator("#dlg-conta").evaluate((d) => d.open));
await pg.locator("#dlg-conta [data-fechar]").first().click(); await pg.waitForEvent("load"); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(400);
confere("ao fechar a janela, a página se atualiza sozinha, uma vez", cargas === 1 && (await pg.evaluate(() => sessionStorage.getItem("gp-atualizou-para"))) === "2099.01.01-1");
confere("se a recarga não trouxe a versão nova, fica o aviso, sem recarregar em laço", (await pg.locator("#aviso-versao").isVisible()) && (await txt("#aviso-versao")).includes("Há uma versão nova do site.") && cargas === 1);
await pg.locator("#aviso-versao button").click(); await pg.waitForEvent("load"); await pg.waitForSelector("#app:not([hidden])");
confere("o botão Atualizar do aviso recarrega a página", cargas === 2);
await pg.evaluate(() => sessionStorage.clear()); cargas = 0;
await pg.reload(); await pg.waitForEvent("load"); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(400);
confere("versão nova com a pessoa livre: atualiza sozinha ao abrir, sem aviso antes", cargas === 2 && (await pg.evaluate(() => sessionStorage.getItem("gp-atualizou-para"))) === "2099.01.01-1");
await pg.unroute(/\/js\/versao\.js\?t=/);
// Visão do administrador: vê os projetos de que não faz parte e o que é deles, somente para leitura
await pg.evaluate(() => sessionStorage.clear()); await pg.setViewportSize({ width: 1440, height: 900 });
await pg.goto("http://localhost:8123/?visao=1"); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(300);
await pg.click("[data-visao='projetos']");
confere("admin: o quadro de Projetos mostra o projeto de outra pessoa", (await txt("#visao-projetos")).includes("Projeto do Bruno"));
confere("admin: o cartão do projeto de outra pessoa não se arrasta, e o dele sim", (await pg.locator("#visao-projetos .cartao", { hasText: "Projeto do Bruno" }).evaluate((c) => c.draggable)) === false && (await pg.locator("#visao-projetos .cartao", { hasText: "Projeto Exemplo" }).evaluate((c) => c.draggable)) === true);
await pg.getByText("Projeto do Bruno").first().click();
confere("admin: o projeto de outra pessoa avisa que é somente para leitura", (await txt("#p-membros-nota")) === "Você vê este projeto como administrador, somente para leitura." && (await txt("#p-janela")) === "Projeto");
confere("admin: no projeto de outra pessoa, os campos ficam desligados", await pg.locator("#p-titulo").isDisabled() && await pg.locator("#p-descricao").isDisabled() && await pg.locator("#p-coluna").isDisabled() && await pg.locator("#p-prioridade").isDisabled() && await pg.locator("#p-prazo").isDisabled() && await pg.locator("#p-responsavel").isDisabled());
confere("admin: no projeto de outra pessoa, não há Salvar, Excluir, Nova tarefa nem registro de ideia", await pg.locator("#form-projeto button[type=submit]").isHidden() && await pg.locator("#p-excluir").isHidden() && await pg.locator("#p-adicionar").isHidden() && await pg.locator("#p-ideia-nova").isHidden() && (await txt("#form-projeto .acoes [data-fechar]")) === "Fechar");
confere("admin: no projeto de outra pessoa, vê as tarefas e as ideias dele", (await txt("#p-lista")).includes("Tarefa do Bruno") && (await txt("#p-ideias-lista")).includes("Ideia do Bruno no projeto dele"));
let nAdm = (await grav()).length;
await pg.locator("#p-ideias-lista").getByText("Ideia do Bruno no projeto dele").click(); await pg.waitForTimeout(200);
confere("admin: na ideia de projeto de outra pessoa, lê sem apoiar, comentar nem salvar", await pg.locator("#i-apoiar").isHidden() && await pg.locator("#i-comentario-texto").isHidden() && await pg.locator("#i-salvar").isHidden() && await pg.locator("#i-status").isDisabled() && (await txt("#i-historico")).includes("somente para leitura"));
await pg.locator("#dlg-ideia [data-fechar]:visible").first().click();
await pg.locator("#dlg-projeto [data-fechar]:visible").first().click();
await pg.getByText("Projeto Exemplo").first().click();
confere("admin: no projeto dele, tudo continua liberado", !(await txt("#p-membros-nota")).includes("como administrador") && await pg.locator("#p-titulo").isEnabled() && await pg.locator("#form-projeto button[type=submit]").isVisible() && await pg.locator("#p-adicionar").isVisible() && await pg.locator("#p-ideia-nova").isVisible() && (await txt("#form-projeto .acoes [data-fechar]")) === "Cancelar");
await pg.locator("#dlg-projeto [data-fechar]:visible").first().click();
await pg.click("[data-visao='tarefas']"); await pg.click("[data-modo='quadro']");
confere("admin: o quadro de Tarefas mostra a tarefa de projeto de outra pessoa, sem arrastar", (await txt("#visao-tarefas")).includes("Tarefa do Bruno") && (await pg.locator("#visao-tarefas .cartao", { hasText: "Tarefa do Bruno" }).evaluate((c) => c.draggable)) === false);
await pg.getByText("Tarefa do Bruno").first().click();
confere("admin: a tarefa de outra pessoa abre somente para leitura", (await txt("#t-janela")) === "Tarefa" && await pg.locator("#t-titulo").isDisabled() && await pg.locator("#t-coluna").isDisabled() && await pg.locator("#t-responsavel").isDisabled() && await pg.locator("#form-tarefa button[type=submit]").isHidden() && await pg.locator("#t-concluir").isHidden() && await pg.locator("#t-excluir").isHidden() && (await txt("#t-visivel")).includes("somente para leitura"));
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click();
await pg.click("#nova-tarefa");
confere("admin: tarefa nova abre liberada, e só oferece os projetos de que ele faz parte", await pg.locator("#t-titulo").isEnabled() && await pg.locator("#form-tarefa button[type=submit]").isVisible() && !(await txt("#t-projeto")).includes("Projeto do Bruno") && (await txt("#t-projeto")).includes("Projeto Exemplo"));
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click();
await pg.click("[data-visao='ideias']");
await pg.click("#ideia-nova"); await pg.waitForTimeout(100);
confere("admin: a aba Ideias mostra a ideia de projeto de outra pessoa, e a nova ideia só oferece os projetos dele", (await txt("#lista-ideias")).includes("Ideia do Bruno no projeto dele") && !(await pg.locator("#i-projeto").innerText()).includes("Projeto do Bruno") && (await txt("#filtro-ideia-projeto")).includes("Projeto do Bruno"));
await pg.locator("#dlg-ideia [data-fechar]:visible").first().click(); await pg.waitForTimeout(100);
confere("admin: nada foi mandado gravar nos projetos dos outros", (await grav()).length === nAdm);
// O mesmo no celular: leitura sem "Nova tarefa", com "Ver detalhes" no lugar de "Editar" e o campo "Coluna" desligado
await pg.setViewportSize({ width: 390, height: 844 }); await pg.goto("http://localhost:8123/?visao=1"); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(300);
await pg.getByText("Projeto do Bruno").first().click(); await pg.waitForTimeout(200);
confere("admin, celular: a leitura do projeto de outra pessoa não deixa mudar nada", await pg.locator("#lp-coluna").isDisabled() && await pg.locator("#lp-nova").isHidden() && await pg.locator("#lp-ideia-nova").isHidden() && (await txt("#lp-editar")) === "Ver detalhes" && (await txt("#lp-historico")).includes("somente para leitura"));
await pg.locator("#lp-lista").getByText("Tarefa do Bruno").click(); await pg.waitForTimeout(200);
confere("admin, celular: a leitura da tarefa de outra pessoa não deixa mudar nada", await pg.locator("#l-coluna").isDisabled() && await pg.locator("#l-concluir").isHidden() && (await txt("#l-editar")) === "Ver detalhes");
await pg.locator("#dlg-tarefa [data-fechar]:visible").first().click();
await pg.locator("#dlg-projeto [data-fechar]:visible, #dlg-projeto .voltar:visible").first().click();
// Fluxo de status das ideias (etapa I6)
await pg.setViewportSize({ width: 1440, height: 900 }); await pg.goto("http://localhost:8123/?fluxo=1"); await pg.waitForSelector("#app:not([hidden])"); await pg.waitForTimeout(300);
await pg.click("[data-visao='ideias']");
confere("I6: a aba Ideias tem as abas Abertas, Executadas e Descartadas, com a contagem de cada uma", (await pg.locator("#abas-ideias button").allInnerTexts()).join("|") === "Abertas (6)|Executadas (1)|Descartadas (1)" && await pg.locator("#filtro-ideia-status-campo").isVisible());
await pg.locator("#abas-ideias button", { hasText: "Executadas" }).click();
confere("I6: a aba Executadas mostra só a ideia executada, com a etiqueta Executada, e esconde o filtro de status", (await pg.locator("#lista-ideias .linha-tarefa .nome").allInnerTexts()).join("|") === "Ideia executada de exemplo" && (await pg.locator("#lista-ideias .chip.status-executada").innerText()) === "Executada" && !(await pg.locator("#filtro-ideia-status-campo").isVisible()));
await pg.locator("#abas-ideias button", { hasText: "Abertas" }).click();
const opcoes = async () => (await pg.locator("#i-status option").allInnerTexts()).join("|");
// Responsável pelo projeto (Ana), ideia aprovada de outra pessoa
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia aprovada do Bruno" }).click();
confere("I6: o responsável vê, na ideia Aprovada, os passos: voltar, executar ou descartar", (await opcoes()) === "Aprovada|Em análise|Executada|Descartada" && await pg.locator("#i-status").isEnabled());
confere("I6: o responsável altera o texto com a ideia Aprovada, mesmo sem ser o autor", await pg.locator("#i-titulo").isVisible() && await pg.locator("#i-titulo").isEnabled());
confere("I6: o histórico mostra a mudança de status e a de texto, com quem fez", (await pg.locator("#i-registro-lista li").count()) === 2 && /Status: Em análise → Aprovada/.test(await txt("#i-registro-lista")) && /Título: "Ideia do Bruno" → "Ideia aprovada do Bruno"/.test(await txt("#i-registro-lista")) && (await txt("#i-registro-lista")).includes("Ana Teste"));
confere("I6: quem não é o autor não vê o campo Projeto", !(await pg.locator("#i-campo-projeto").isVisible()));
await pg.selectOption("#i-status", "executada"); n3 = (await grav()).length; await pg.locator("#i-salvar").click(); await pg.waitForTimeout(200);
confere("I6: Salvar manda só o novo status", (await grav()).slice(n3).some((x) => x[0] === "ideias" && x[1] === "update" && Object.keys(x[2]).join() === "status" && x[2].status === "executada"));
// Ideia executada: só pode voltar para Aprovada
await fechaJanelas();
await pg.locator("#abas-ideias button", { hasText: "Executadas" }).click(); await pg.locator("#lista-ideias .abrir", { hasText: "Ideia executada de exemplo" }).click();
confere("I6: a ideia Executada só volta para Aprovada (não pode ser descartada)", (await opcoes()) === "Executada|Aprovada");
await fechaJanelas();
// Descartada: só volta para Em análise
await pg.locator("#abas-ideias button", { hasText: "Descartadas" }).click(); await pg.locator("#lista-ideias .abrir", { hasText: "Ideia descartada no projeto" }).click();
confere("I6: a ideia Descartada só volta para Em análise", (await opcoes()) === "Descartada|Em análise");
await fechaJanelas(); await pg.locator("#abas-ideias button", { hasText: "Abertas" }).click();
// Ideia que deu origem a tarefa: não pode ser descartada
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia que virou tarefa" }).click();
confere("I6: a ideia que deu origem a uma tarefa não oferece Descartada, e a tela explica", (await opcoes()) === "Aprovada|Em análise|Executada" && (await txt("#i-status-nota")).includes("não pode ser descartada"));
await fechaJanelas();
// Quem participa do projeto sem ser o responsável (Ana, no projeto do Bruno)
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia da Ana no projeto do Bruno" }).click();
confere("I6: o autor que não é o responsável só passa entre Nova e Em análise, e a tela avisa", (await opcoes()) === "Nova|Em análise" && (await txt("#i-status-nota")).includes("só o responsável pelo projeto") && await pg.locator("#i-titulo").isEnabled());
await fechaJanelas();
await pg.locator("#lista-ideias .abrir", { hasText: "Ideia aprovada da Ana no projeto do Bruno" }).click();
confere("I6: com a ideia Aprovada, o autor que não é o responsável não muda o status nem o texto", await pg.locator("#i-status").isDisabled() && !(await pg.locator("#i-titulo").isVisible()) && (await txt("#i-titulo-leitura")) === "Ideia aprovada da Ana no projeto do Bruno" && await pg.locator("#i-salvar").isHidden() && (await txt("#i-cancelar")) === "Fechar" && await pg.locator("#i-excluir").isVisible());
confere("I6: com a ideia Aprovada, o campo Projeto do autor fica travado, com a explicação", await pg.locator("#i-projeto").isDisabled() && (await txt("#i-projeto-nota")).startsWith("Só dá para vincular ou desvincular"));
await fechaJanelas();
confere("I6: nada mais foi mandado gravar", (await grav()).length === n3 + 1);

confere("nenhum erro no console", erros.length === 0); erros.forEach((e) => console.log("   " + e));
console.log(`RESULTADO: ${ok} ok, ${falhas} falhas`); await b.close(); srv.close();
process.exit(falhas ? 1 : 0);
